/**
 * Monk Journey PWA Service Worker
 * Handles caching and updates for the game
 */

const CACHE_NAME = 'monk-journey-cache';
const CACHE_VERSION = '66';
const CACHE_KEY = CACHE_NAME + '-v' + CACHE_VERSION;


// Total cache size in bytes and MB
const TOTAL_CACHE_SIZE_BYTES = 8983151;
const TOTAL_CACHE_SIZE_MB = 8.57;

// Assets to cache
const ASSETS_TO_CACHE = [
  '',
  'manifest.json',
  'css/animations.css',
  'css/camera-control.css',
  'css/death-screen.css',
  'css/dialog.css',
  'css/difficulty-menu.css',
  'css/game-menu.css',
  'css/game.css',
  'css/guide.css',
  'css/hud/common.css',
  'css/hud/effects-container.css',
  'css/hud/enemy-health.css',
  'css/hud/joystick.css',
  'css/hud/layout.css',
  'css/hud/minimap.css',
  'css/hud/player-stats.css',
  'css/hud/quest-log.css',
  'css/hud/skills.css',
  'css/hud/status-effects.css',
  'css/hud-manager.css',
  'css/icons.css',
  'css/initial-loading.css',
  'css/inventory.css',
  'css/item-popup.css',
  'css/loading-screen.css',
  'css/login-modal.css',
  'css/main.css',
  'css/map-selector.css',
  'css/multiplayer.css',
  'css/notifications.css',
  'css/orientation-message.css',
  'css/reset.css',
  'css/settings/base.css',
  'css/settings/buttons.css',
  'css/settings/controls.css',
  'css/settings/enemy-preview.css',
  'css/settings/forms.css',
  'css/settings/item-preview.css',
  'css/settings/mobile.css',
  'css/settings/model-preview.css',
  'css/settings/skills-preview.css',
  'css/settings/tabs.css',
  'css/settings-menu.css',
  'css/skill-preview.css',
  'css/skill-selection.css',
  'css/skill-tree.css',
  'css/teleport-manager.css',
  'css/utilities.css',
  'css/variables.css',
  'js/AudioManager.js',
  'js/CollisionManager.js',
  'js/EffectsManager.js',
  'js/InputHandler.js',
  'js/InteractionResultHandler.js',
  'js/Main.js',
  'js/PerformanceManager.js',
  'js/QuestManager.js',
  'js/UIComponent.js',
  'js/effects/EffectObjectPool.js',
  'js/enemies/Enemy.js',
  'js/enemies/EnemyManager.js',
  'js/enemies/models/AncientConstructModel.js',
  'js/enemies/models/AncientTreantModel.js',
  'js/enemies/models/AncientYetiModel.js',
  'js/enemies/models/CorruptedTreantModel.js',
  'js/enemies/models/DefaultModel.js',
  'js/enemies/models/DemonModel.js',
  'js/enemies/models/EnemyModel.js',
  'js/enemies/models/EnemyModelFactory.js',
  'js/enemies/models/EnemyModelRegistry.js',
  'js/enemies/models/FireElementalModel.js',
  'js/enemies/models/FrostElementalModel.js',
  'js/enemies/models/FrostMonarchModel.js',
  'js/enemies/models/FrostTitanModel.js',
  'js/enemies/models/InfernalGolemModel.js',
  'js/enemies/models/InfernoLordModel.js',
  'js/enemies/models/MoltenBehemothModel.js',
  'js/enemies/models/MountainTrollModel.js',
  'js/enemies/models/NecromancerModel.js',
  'js/enemies/models/ShadowBeastModel.js',
  'js/enemies/models/SimpleEnemyModel.js',
  'js/enemies/models/SkeletonArcherModel.js',
  'js/enemies/models/SkeletonModel.js',
  'js/enemies/models/SpiderQueenModel.js',
  'js/enemies/models/SwampHorrorModel.js',
  'js/enemies/models/SwampWitchModel.js',
  'js/enemies/models/VoidWraithModel.js',
  'js/enemies/models/ZombieBruteModel.js',
  'js/enemies/models/ZombieModel.js',
  'js/items/Item.js',
  'js/items/ItemDropManager.js',
  'js/items/ItemGenerator.js',
  'js/items/models/ItemModel.js',
  'js/items/models/ItemModelFactory.js',
  'js/items/models/accessory/AmuletModel.js',
  'js/items/models/accessory/RingModel.js',
  'js/items/models/accessory/TalismanModel.js',
  'js/items/models/armor/BeltModel.js',
  'js/items/models/armor/BootsModel.js',
  'js/items/models/armor/GlovesModel.js',
  'js/items/models/armor/HelmetModel.js',
  'js/items/models/armor/RobeModel.js',
  'js/items/models/consumable/FoodModel.js',
  'js/items/models/consumable/PotionModel.js',
  'js/items/models/consumable/ScrollModel.js',
  'js/items/models/weapons/DaggerModel.js',
  'js/items/models/weapons/FistModel.js',
  'js/items/models/weapons/StaffModel.js',
  'js/player/Player.js',
  'js/player/PlayerAttackEffect.js',
  'js/player/PlayerCombat.js',
  'js/player/PlayerInventory.js',
  'js/player/PlayerModel.js',
  'js/player/PlayerMovement.js',
  'js/player/PlayerSkills.js',
  'js/player/PlayerState.js',
  'js/player/PlayerStats.js',
  'js/player/PlayerStatusEffects.js',
  'js/skills/BleedingEffect.js',
  'js/skills/BreathOfHeavenEffect.js',
  'js/skills/BulBreathOfHeavenEffect.js',
  'js/skills/BulPalmEffect.js',
  'js/skills/BulShadowCloneEffect.js',
  'js/skills/CycloneStrikeEffect.js',
  'js/skills/DeadlyReachEffect.js',
  'js/skills/ExplodingPalmEffect.js',
  'js/skills/FistOfThunderEffect.js',
  'js/skills/FlyingDragonEffect.js',
  'js/skills/FlyingKickEffect.js',
  'js/skills/ImprisonedFistsEffect.js',
  'js/skills/InnerSanctuaryEffect.js',
  'js/skills/MysticAllyEffect.js',
  'js/skills/SevenSidedStrikeEffect.js',
  'js/skills/ShieldOfZenEffect.js',
  'js/skills/Skill.js',
  'js/skills/SkillEffect.js',
  'js/skills/SkillEffectFactory.js',
  'js/skills/SkillEffectRegistry.js',
  'js/skills/WaveOfLightEffect.js',
  'js/skills/WaveStrikeEffect.js',
  'js/skills/variants/BreathOfHeaven/CircleOfLifeEffect.js',
  'js/skills/variants/BreathOfHeaven/InfusedWithLightEffect.js',
  'js/skills/variants/BreathOfHeaven/RadiantBreathEffect.js',
  'js/skills/variants/BreathOfHeaven/SoothingMistEffect.js',
  'js/skills/variants/BreathOfHeaven/ZephyrsGraceEffect.js',
  'js/skills/variants/BulPalm/BulPalmCrossEffect.js',
  'js/skills/variants/BulPalm/BulPalmRainEffect.js',
  'js/skills/variants/BulPalm/StormOfPalmsEffect.js',
  'js/skills/variants/CycloneStrike/EyeOfTheStormEffect.js',
  'js/skills/variants/CycloneStrike/MysticWindsEffect.js',
  'js/skills/variants/CycloneStrike/PathOfTheStormEffect.js',
  'js/skills/variants/CycloneStrike/SandstormEffect.js',
  'js/skills/variants/CycloneStrike/StormSpiritEffect.js',
  'js/skills/variants/CycloneStrike/TempestRushEffect.js',
  'js/skills/variants/CycloneStrike/TempestsHeartEffect.js',
  'js/skills/variants/CycloneStrike/TornadoEffect.js',
  'js/skills/variants/CycloneStrike/VortexEffect.js',
  'js/skills/variants/CycloneStrike/backup/FrigidCycloneEffect.js',
  'js/skills/variants/ExplodingPalm/BleedingPalmEffect.js',
  'js/skills/variants/ExplodingPalm/BreathOfIncenseEffect.js',
  'js/skills/variants/ExplodingPalm/ConcussivePalmEffect.js',
  'js/skills/variants/ExplodingPalm/CripplingInsightEffect.js',
  'js/skills/variants/ExplodingPalm/FieryPalmEffect.js',
  'js/skills/variants/ExplodingPalm/IcyPalmEffect.js',
  'js/skills/variants/ExplodingPalm/PathOfThePresentEffect.js',
  'js/skills/variants/ExplodingPalm/ReachingRebukeEffect.js',
  'js/skills/variants/ExplodingPalm/ScoldingStormEffect.js',
  'js/skills/variants/ExplodingPalm/ShockingPalmEffect.js',
  'js/skills/variants/FlyingDragon/DragonFlightEffect.js',
  'js/skills/variants/FlyingDragon/GaleDragonEffect.js',
  'js/skills/variants/FlyingDragon/InfernoDragonEffect.js',
  'js/skills/variants/FlyingDragon/ShadowDragonEffect.js',
  'js/skills/variants/FlyingDragon/ThunderDragonEffect.js',
  'js/skills/variants/FlyingKick/BlazingKickEffect.js',
  'js/skills/variants/FlyingKick/CycloneKickEffect.js',
  'js/skills/variants/FlyingKick/GaleKickEffect.js',
  'js/skills/variants/FlyingKick/GracesBountyEffect.js',
  'js/skills/variants/FlyingKick/MantleOfTheCraneEffect.js',
  'js/skills/variants/FlyingKick/MomentumFlowEffect.js',
  'js/skills/variants/FlyingKick/ShadowKickEffect.js',
  'js/skills/variants/FlyingKick/SpokesOfTheWheelEffect.js',
  'js/skills/variants/FlyingKick/ThunderousKickEffect.js',
  'js/skills/variants/FlyingKick/TigersFlightEffect.js',
  'js/skills/variants/ImprisonedFists/FieryChainsEffect.js',
  'js/skills/variants/ImprisonedFists/FrozenShacklesEffect.js',
  'js/skills/variants/ImprisonedFists/GaleChainsEffect.js',
  'js/skills/variants/ImprisonedFists/ShadowBindEffect.js',
  'js/skills/variants/ImprisonedFists/ThunderousGripEffect.js',
  'js/skills/variants/InnerSanctuary/CircleOfWrathEffect.js',
  'js/skills/variants/InnerSanctuary/ForbiddenPalaceEffect.js',
  'js/skills/variants/InnerSanctuary/SafeHavenEffect.js',
  'js/skills/variants/InnerSanctuary/SanctifiedGroundEffect.js',
  'js/skills/variants/InnerSanctuary/TempleOfProtectionEffect.js',
  'js/skills/variants/MysticAllies/FireAlliesEffect.js',
  'js/skills/variants/MysticAllies/WaterAlliesEffect.js',
  'js/skills/variants/SevenSidedStrike/FistOfFuryEffect.js',
  'js/skills/variants/SevenSidedStrike/InnerPeaceEffect.js',
  'js/skills/variants/SevenSidedStrike/PandemoniumEffect.js',
  'js/skills/variants/SevenSidedStrike/ShadowAssaultEffect.js',
  'js/skills/variants/SevenSidedStrike/SustainedAssaultEffect.js',
  'js/skills/variants/ShieldOfZen/DiamondAuraEffect.js',
  'js/skills/variants/ShieldOfZen/RetributionAuraEffect.js',
  'js/skills/variants/ShieldOfZen/SpiritualProtectionEffect.js',
  'js/skills/variants/ShieldOfZen/TranscendenceEffect.js',
  'js/skills/variants/WaveOfLight/ExplosiveLightEffect.js',
  'js/skills/variants/WaveOfLight/LightningBellEffect.js',
  'js/skills/variants/WaveOfLight/LightningBurstEffect.js',
  'js/skills/variants/WaveOfLight/PillarOfTheLightEffect.js',
  'js/skills/variants/WaveOfLight/PillarOfTheSunEffect.js',
  'js/skills/variants/WaveOfLight/WallOfLightEffect.js',
  'js/skills/variants/WaveStrike/FrozenWaveEffect.js',
  'js/skills/variants/WaveStrike/ThunderWaveEffect.js',
  'js/skills/variants/WaveStrike/TidalWaveEffect.js',
  'js/game/Game.js',
  'js/game/GameEvents.js',
  'js/game/GameState.js',
  'js/game/LoadingManager.js',
  'js/game/SceneOptimizer.js',
  'js/hud-manager/CameraControlUI.js',
  'js/hud-manager/DeathScreenUI.js',
  'js/hud-manager/DialogUI.js',
  'js/hud-manager/EnemyUI.js',
  'js/hud-manager/HUDGuide.js',
  'js/hud-manager/HUDManager.js',
  'js/hud-manager/HomeUI.js',
  'js/hud-manager/InventoryButton.js',
  'js/hud-manager/InventoryUI.js',
  'js/hud-manager/MapSelectionUI.js',
  'js/hud-manager/MiniMapButton.js',
  'js/hud-manager/MiniMapUI.js',
  'js/hud-manager/NotificationsUI.js',
  'js/hud-manager/PlayerUI.js',
  'js/hud-manager/PortalButton.js',
  'js/hud-manager/QuestLogUI.js',
  'js/hud-manager/SkillSelectionButton.js',
  'js/hud-manager/SkillSelectionUI.js',
  'js/hud-manager/SkillTreeButton.js',
  'js/hud-manager/SkillTreeUI.js',
  'js/hud-manager/SkillsUI.js',
  'js/hud-manager/VirtualJoystickUI.js',
  'js/interaction/InteractionSystem.js',
  'js/menu-system/ControlsDisplay.js',
  'js/menu-system/EnemyPreview.js',
  'js/menu-system/GameMenu.js',
  'js/menu-system/IMenu.js',
  'js/menu-system/ItemPreview.js',
  'js/menu-system/MenuManager.js',
  'js/menu-system/ModelPreview.js',
  'js/menu-system/SettingsMenu.js',
  'js/menu-system/settings-menu/AudioTab.js',
  'js/menu-system/settings-menu/CharacterModelTab.js',
  'js/menu-system/settings-menu/ControlsTab.js',
  'js/menu-system/settings-menu/DebugTab.js',
  'js/menu-system/settings-menu/EnemyPreviewTab.js',
  'js/menu-system/settings-menu/GameplayTab.js',
  'js/menu-system/settings-menu/ItemPreviewTab.js',
  'js/menu-system/settings-menu/ReleaseTab.js',
  'js/menu-system/settings-menu/SettingsTab.js',
  'js/menu-system/settings-menu/SkillPreview.js',
  'js/menu-system/settings-menu/SkillsPreviewTab.js',
  'js/multiplayer/BinarySerializer.js',
  'js/multiplayer/MultiplayerConnectionManager.js',
  'js/multiplayer/MultiplayerManager.js',
  'js/multiplayer/MultiplayerUIManager.js',
  'js/multiplayer/RemotePlayer.js',
  'js/multiplayer/RemotePlayerManager.js',
  'js/save-manager/GoogleAuthManager.js',
  'js/save-manager/GoogleDriveAdapter.js',
  'js/save-manager/ISaveSystem.js',
  'js/save-manager/IStorageAdapter.js',
  'js/save-manager/LocalStorageAdapter.js',
  'js/save-manager/SaveManager.js',
  'js/save-manager/StorageService.js',
  'js/save-manager/serializers/InventorySerializer.js',
  'js/save-manager/serializers/PlayerSerializer.js',
  'js/save-manager/serializers/QuestSerializer.js',
  'js/save-manager/serializers/SettingsSerializer.js',
  'js/save-manager/utils/SaveOperationProgress.js',
  'js/utils/AnimationUtils.js',
  'js/utils/GeometryFactory.js',
  'js/utils/SkillTreeUtils.js',
  'js/world/WorldManager.js',
  'js/world/environment/AlpineFlower.js',
  'js/world/environment/AncientAltar.js',
  'js/world/environment/AncientArtifact.js',
  'js/world/environment/AncientStone.js',
  'js/world/environment/AncientTree.js',
  'js/world/environment/AshPile.js',
  'js/world/environment/BerryBush.js',
  'js/world/environment/BogPit.js',
  'js/world/environment/BrokenColumn.js',
  'js/world/environment/Bush.js',
  'js/world/environment/CrystalFormation.js',
  'js/world/environment/CrystalOutcrop.js',
  'js/world/environment/DesertPlant.js',
  'js/world/environment/DesertShrine.js',
  'js/world/environment/EmberVent.js',
  'js/world/environment/EnvironmentFactory.js',
  'js/world/environment/EnvironmentManager.js',
  'js/world/environment/EnvironmentObject.js',
  'js/world/environment/FairyCircle.js',
  'js/world/environment/FallenLog.js',
  'js/world/environment/Fern.js',
  'js/world/environment/Flower.js',
  'js/world/environment/FogManager.js',
  'js/world/environment/ForestDebris.js',
  'js/world/environment/ForestFlower.js',
  'js/world/environment/ForestShrine.js',
  'js/world/environment/ForgottenStatue.js',
  'js/world/environment/Fountain.js',
  'js/world/environment/Foutain.js',
  'js/world/environment/GiantMushroom.js',
  'js/world/environment/GlowingFlowers.js',
  'js/world/environment/GlowingMushroom.js',
  'js/world/environment/IceFormation.js',
  'js/world/environment/IceShard.js',
  'js/world/environment/LavaFeature.js',
  'js/world/environment/LavaRock.js',
  'js/world/environment/LilyPad.js',
  'js/world/environment/MagicCircle.js',
  'js/world/environment/MagicalFlower.js',
  'js/world/environment/MagicalStone.js',
  'js/world/environment/Market.js',
  'js/world/environment/Moss.js',
  'js/world/environment/MountainCave.js',
  'js/world/environment/MountainPass.js',
  'js/world/environment/MountainRock.js',
  'js/world/environment/Mushroom.js',
  'js/world/environment/MushroomCluster.js',
  'js/world/environment/MysteriousPortal.js',
  'js/world/environment/Oasis.js',
  'js/world/environment/Obsidian.js',
  'js/world/environment/ObsidianFormation.js',
  'js/world/environment/OvergrownRuin.js',
  'js/world/environment/PineTree.js',
  'js/world/environment/Plaza.js',
  'js/world/environment/RarePlant.js',
  'js/world/environment/Rock.js',
  'js/world/environment/RockFormation.js',
  'js/world/environment/RuneStone.js',
  'js/world/environment/Shrine.js',
  'js/world/environment/SkyManager.js',
  'js/world/environment/SmallCrystal.js',
  'js/world/environment/SmallMushroom.js',
  'js/world/environment/SmallPeak.js',
  'js/world/environment/SmallPlant.js',
  'js/world/environment/SnowPatch.js',
  'js/world/environment/Square.js',
  'js/world/environment/Stairs.js',
  'js/world/environment/Statue.js',
  'js/world/environment/StatueFragment.js',
  'js/world/environment/StoneCircle.js',
  'js/world/environment/Stump.js',
  'js/world/environment/SwampDebris.js',
  'js/world/environment/SwampLight.js',
  'js/world/environment/SwampPlant.js',
  'js/world/environment/SwampTree.js',
  'js/world/environment/TallGrass.js',
  'js/world/environment/Tree.js',
  'js/world/environment/TreeCluster.js',
  'js/world/environment/TreeWithLOD.js',
  'js/world/environment/Treehouse.js',
  'js/world/environment/WaterFeature.js',
  'js/world/environment/Waterfall.js',
  'js/world/environment/Well.js',
  'js/world/interactive/BossSpawnPoint.js',
  'js/world/interactive/InteractiveObjectManager.js',
  'js/world/interactive/QuestMarker.js',
  'js/world/interactive/TreasureChest.js',
  'js/world/lighting/LightingManager.js',
  'js/world/managers/MemoryManager.js',
  'js/world/managers/PerformanceManager.js',
  'js/world/managers/WaveManager.js',
  'js/world/paths/BranchingPath.js',
  'js/world/paths/CircularPath.js',
  'js/world/paths/CurvedPath.js',
  'js/world/paths/NaturalPath.js',
  'js/world/paths/Path.js',
  'js/world/paths/PathFactory.js',
  'js/world/paths/PathManager.js',
  'js/world/paths/SpiralPath.js',
  'js/world/paths/StraightPath.js',
  'js/world/structures/Bridge.js',
  'js/world/structures/Building.js',
  'js/world/structures/DarkSanctum.js',
  'js/world/structures/Mountain.js',
  'js/world/structures/Ruins.js',
  'js/world/structures/Shrine.js',
  'js/world/structures/StructureFactory.js',
  'js/world/structures/StructureManager.js',
  'js/world/structures/Tower.js',
  'js/world/structures/Village.js',
  'js/world/teleport/PortalModelFactory.js',
  'js/world/teleport/TeleportManager.js',
  'js/world/terrain/TerrainManager.js',
  'js/world/utils/EnvironmentObjectPool.js',
  'js/world/utils/RandomGenerator.js',
  'js/world/utils/SpatialGrid.js',
  'js/world/zones/ZoneManager.js',
  'images/apple-touch-icon.png',
  'images/favicon-16x16.png',
  'images/favicon-32x32.png',
  'images/favicon.ico',
  'images/home.jpg',
  'images/logo-192.png',
  'images/logo-512.png',
  'assets/audio/ally_dismiss.mp3',
  'assets/audio/ally_summon.mp3',
  'assets/audio/attack.mp3',
  'assets/audio/barrier_dissipate.mp3',
  'assets/audio/barrier_form.mp3',
  'assets/audio/battle_theme.mp3',
  'assets/audio/bell_fade.mp3',
  'assets/audio/bell_ring.mp3',
  'assets/audio/boss_death.mp3',
  'assets/audio/boss_spawn.mp3',
  'assets/audio/boss_theme.mp3',
  'assets/audio/breath_of_heaven.mp3',
  'assets/audio/button_click.mp3',
  'assets/audio/chain_impact.mp3',
  'assets/audio/chains_break.mp3',
  'assets/audio/chest_open.mp3',
  'assets/audio/cyclone_strike.mp3',
  'assets/audio/danger_warning.mp3',
  'assets/audio/deadly_reach_cast.mp3',
  'assets/audio/deadly_reach_end.mp3',
  'assets/audio/deadly_reach_impact.mp3',
  'assets/audio/divine_echo.mp3',
  'assets/audio/door_open.mp3',
  'assets/audio/dragon_land.mp3',
  'assets/audio/dragon_strike.mp3',
  'assets/audio/effect_damage_boost.mp3',
  'assets/audio/effect_defense_boost.mp3',
  'assets/audio/effect_invulnerability.mp3',
  'assets/audio/effect_invulnerable.mp3',
  'assets/audio/effect_regeneration.mp3',
  'assets/audio/effect_slow.mp3',
  'assets/audio/effect_speed_boost.mp3',
  'assets/audio/enemy_attack.mp3',
  'assets/audio/enemy_death.mp3',
  'assets/audio/enemy_hit.mp3',
  'assets/audio/exploding_palm.mp3',
  'assets/audio/fist_of_thunder.mp3',
  'assets/audio/flying_dragon.mp3',
  'assets/audio/flying_kick.mp3',
  'assets/audio/healing_pulse.mp3',
  'assets/audio/imprisoned_fists.mp3',
  'assets/audio/inner_sanctuary.mp3',
  'assets/audio/inventory_open.mp3',
  'assets/audio/item_pickup.mp3',
  'assets/audio/kick_impact.mp3',
  'assets/audio/kick_land.mp3',
  'assets/audio/level_up.mp3',
  'assets/audio/main_theme.mp3',
  'assets/audio/mark_applied.mp3',
  'assets/audio/massive_explosion.mp3',
  'assets/audio/mystic_ally.mp3',
  'assets/audio/player_death.mp3',
  'assets/audio/player_hit.mp3',
  'assets/audio/rapid_strike.mp3',
  'assets/audio/seven_sided_strike.mp3',
  'assets/audio/strike_complete.mp3',
  'assets/audio/teleport.mp3',
  'assets/audio/thunder_echo.mp3',
  'assets/audio/thunder_strike.mp3',
  'assets/audio/water_dissipate.mp3',
  'assets/audio/water_impact.mp3',
  'assets/audio/wave_of_light.mp3',
  'assets/audio/wave_strike.mp3',
  'assets/audio/wind_dissipate.mp3',
  'assets/audio/wind_pull.mp3',
  'assets/effects/buddha.glb',
  'assets/effects/flying-dragon.glb',
  'assets/images/background.jpg',
  'assets/models/monk-v3.glb',
  'assets/models/monk.glb'
];

// File sizes in bytes for progress reporting
const FILE_SIZES =   {
    "": 33696,
    "manifest.json": 571,
    "css/animations.css": 916,
    "css/dialog.css": 545,
    "css/game-menu.css": 5419,
    "css/game.css": 265,
    "css/hud-manager.css": 13143,
    "css/icons.css": 718,
    "css/initial-loading.css": 873,
    "css/inventory.css": 7981,
    "css/loading-screen.css": 522,
    "css/main.css": 1255,
    "css/notifications.css": 2324,
    "css/orientation-message.css": 438,
    "css/debug-manager.css": 1496,
    "css/reset.css": 1275,
    "css/settings-menu.css": 20658,
    "css/skill-preview.css": 1780,
    "css/skill-selection.css": 7239,
    "css/skill-tree.css": 8621,
    "css/utilities.css": 3931,
    "css/variables.css": 802,
    "js/AudioManager.js": 22440,
    "js/CollisionManager.js": 12868,
    "js/DifficultyManager.js": 4858,
    "js/EffectsManager.js": 5211,
    "js/InputHandler.js": 15130,
    "js/PerformanceManager.js": 31689,
    "js/QuestManager.js": 18478,
    "js/UIComponent.js": 2476,
    "js/effects/EffectObjectPool.js": 25995,
    "js/enemies/Enemy.js": 19247,
    "js/enemies/EnemyManager.js": 31696,
    "js/enemies/models/CorruptedTreantModel.js": 9617,
    "js/enemies/models/DefaultModel.js": 2282,
    "js/enemies/models/DemonModel.js": 5915,
    "js/enemies/models/EnemyModel.js": 3879,
    "js/enemies/models/EnemyModelFactory.js": 4915,
    "js/enemies/models/FireElementalModel.js": 6885,
    "js/enemies/models/FrostElementalModel.js": 6995,
    "js/enemies/models/FrostTitanModel.js": 7186,
    "js/enemies/models/InfernalGolemModel.js": 4976,
    "js/enemies/models/MountainTrollModel.js": 13144,
    "js/enemies/models/NecromancerModel.js": 7426,
    "js/enemies/models/ShadowBeastModel.js": 3457,
    "js/enemies/models/SimpleEnemyModel.js": 5161,
    "js/enemies/models/SkeletonArcherModel.js": 8968,
    "js/enemies/models/SkeletonModel.js": 7301,
    "js/enemies/models/SwampWitchModel.js": 13036,
    "js/enemies/models/VoidWraithModel.js": 11929,
    "js/enemies/models/ZombieBruteModel.js": 6416,
    "js/enemies/models/ZombieModel.js": 4148,
    "js/player/FallbackPlayerModel.js": 5656,
    "js/player/Player.js": 7886,
    "js/player/PlayerCombat.js": 14398,
    "js/player/PlayerInterface.js": 4557,
    "js/player/PlayerInventory.js": 2993,
    "js/player/PlayerModel.js": 55444,
    "js/player/PlayerMovement.js": 8229,
    "js/player/PlayerSkills.js": 28393,
    "js/player/PlayerState.js": 1428,
    "js/player/PlayerStats.js": 7212,
    "js/skills/BleedingEffect.js": 11889,
    "js/skills/BreathOfHeavenEffect.js": 14617,
    "js/skills/BulBreathOfHeavnEffect.js": 22629,
    "js/skills/BulPalmEffect.js": 28873,
    "js/skills/CycloneStrikeEffect.js": 16059,
    "js/skills/DeadlyReachEffect.js": 14204,
    "js/skills/ExplodingPalmEffect.js": 25429,
    "js/skills/FistOfThunderEffect.js": 15442,
    "js/skills/FlyingDragonEffect.js": 13620,
    "js/skills/FlyingKickEffect.js": 10888,
    "js/skills/ImprisonedFistsEffect.js": 20028,
    "js/skills/InnerSanctuaryEffect.js": 18464,
    "js/skills/MysticAllyEffect.js": 25597,
    "js/skills/SevenSidedStrikeEffect.js": 19501,
    "js/skills/ShieldOfZenEffect.js": 13809,
    "js/skills/Skill.js": 9439,
    "js/skills/SkillEffect.js": 3809,
    "js/skills/SkillEffectFactory.js": 23124,
    "js/skills/TeleportSkillEffect.js": 14179,
    "js/skills/WaveOfLightEffect.js": 21310,
    "js/skills/WaveStrikeEffect.js": 14073,
    "js/skills/variants/BreathOfHeaven/CircleOfLifeEffect.js": 8194,
    "js/skills/variants/BreathOfHeaven/InfusedWithLightEffect.js": 10005,
    "js/skills/variants/BreathOfHeaven/RadiantBreathEffect.js": 6875,
    "js/skills/variants/BreathOfHeaven/SoothingMistEffect.js": 11901,
    "js/skills/variants/BreathOfHeaven/ZephyrsGraceEffect.js": 13678,
    "js/skills/variants/CycloneStrike/EyeOfTheStormEffect.js": 11664,
    "js/skills/variants/CycloneStrike/MysticWindsEffect.js": 15204,
    "js/skills/variants/CycloneStrike/PathOfTheStormEffect.js": 15701,
    "js/skills/variants/CycloneStrike/SandstormEffect.js": 12385,
    "js/skills/variants/CycloneStrike/StormSpiritEffect.js": 14802,
    "js/skills/variants/CycloneStrike/TempestRushEffect.js": 14786,
    "js/skills/variants/CycloneStrike/TempestsHeartEffect.js": 13496,
    "js/skills/variants/CycloneStrike/TornadoEffect.js": 12945,
    "js/skills/variants/CycloneStrike/VortexEffect.js": 13282,
    "js/skills/variants/CycloneStrike/backup/FrigidCycloneEffect.js": 11659,
    "js/skills/variants/ExplodingPalm/BleedingPalmEffect.js": 11637,
    "js/skills/variants/ExplodingPalm/BreathOfIncenseEffect.js": 18171,
    "js/skills/variants/ExplodingPalm/ConcussivePalmEffect.js": 13839,
    "js/skills/variants/ExplodingPalm/CripplingInsightEffect.js": 10811,
    "js/skills/variants/ExplodingPalm/FieryPalmEffect.js": 16074,
    "js/skills/variants/ExplodingPalm/IcyPalmEffect.js": 17082,
    "js/skills/variants/ExplodingPalm/PathOfThePresentEffect.js": 32554,
    "js/skills/variants/ExplodingPalm/ReachingRebukeEffect.js": 16241,
    "js/skills/variants/ExplodingPalm/ScoldingStormEffect.js": 21682,
    "js/skills/variants/ExplodingPalm/ShockingPalmEffect.js": 13982,
    "js/skills/variants/FlyingDragon/DragonFlightEffect.js": 7894,
    "js/skills/variants/FlyingDragon/GaleDragonEffect.js": 16125,
    "js/skills/variants/FlyingDragon/InfernoDragonEffect.js": 15614,
    "js/skills/variants/FlyingDragon/ShadowDragonEffect.js": 16989,
    "js/skills/variants/FlyingDragon/ThunderDragonEffect.js": 19651,
    "js/skills/variants/FlyingKick/BlazingKickEffect.js": 11039,
    "js/skills/variants/FlyingKick/CycloneKickEffect.js": 7717,
    "js/skills/variants/FlyingKick/GaleKickEffect.js": 7961,
    "js/skills/variants/FlyingKick/GracesBountyEffect.js": 19383,
    "js/skills/variants/FlyingKick/MantleOfTheCraneEffect.js": 17057,
    "js/skills/variants/FlyingKick/MomentumFlowEffect.js": 22051,
    "js/skills/variants/FlyingKick/ShadowKickEffect.js": 13669,
    "js/skills/variants/FlyingKick/SpokesOfTheWheelEffect.js": 12233,
    "js/skills/variants/FlyingKick/ThunderousKickEffect.js": 8599,
    "js/skills/variants/FlyingKick/TigersFlightEffect.js": 18694,
    "js/skills/variants/ImprisonedFists/FieryChainsEffect.js": 15451,
    "js/skills/variants/ImprisonedFists/FrozenShacklesEffect.js": 12610,
    "js/skills/variants/ImprisonedFists/GaleChainsEffect.js": 19235,
    "js/skills/variants/ImprisonedFists/ShadowBindEffect.js": 17053,
    "js/skills/variants/ImprisonedFists/ThunderousGripEffect.js": 19033,
    "js/skills/variants/InnerSanctuary/CircleOfWrathEffect.js": 18540,
    "js/skills/variants/InnerSanctuary/ForbiddenPalaceEffect.js": 15287,
    "js/skills/variants/InnerSanctuary/SafeHavenEffect.js": 16656,
    "js/skills/variants/InnerSanctuary/SanctifiedGroundEffect.js": 17614,
    "js/skills/variants/InnerSanctuary/TempleOfProtectionEffect.js": 15813,
    "js/skills/variants/MysticAllies/FireAlliesEffect.js": 17873,
    "js/skills/variants/MysticAllies/WaterAlliesEffect.js": 23391,
    "js/skills/variants/SevenSidedStrike/FistOfFuryEffect.js": 5158,
    "js/skills/variants/SevenSidedStrike/InnerPeaceEffect.js": 11773,
    "js/skills/variants/SevenSidedStrike/PandemoniumEffect.js": 9423,
    "js/skills/variants/SevenSidedStrike/ShadowAssaultEffect.js": 12814,
    "js/skills/variants/SevenSidedStrike/SustainedAssaultEffect.js": 5850,
    "js/skills/variants/ShieldOfZen/DiamondAuraEffect.js": 10050,
    "js/skills/variants/ShieldOfZen/RetributionAuraEffect.js": 19446,
    "js/skills/variants/ShieldOfZen/SpiritualProtectionEffect.js": 15300,
    "js/skills/variants/ShieldOfZen/TranscendenceEffect.js": 11153,
    "js/skills/variants/WaveOfLight/ExplosiveLightEffect.js": 17390,
    "js/skills/variants/WaveOfLight/LightningBellEffect.js": 19940,
    "js/skills/variants/WaveOfLight/LightningBurstEffect.js": 19119,
    "js/skills/variants/WaveOfLight/PillarOfTheLightEffect.js": 10810,
    "js/skills/variants/WaveOfLight/PillarOfTheSunEffect.js": 20649,
    "js/skills/variants/WaveOfLight/WallOfLightEffect.js": 22739,
    "js/skills/variants/WaveStrike/FrozenWaveEffect.js": 20557,
    "js/skills/variants/WaveStrike/ThunderWaveEffect.js": 26335,
    "js/skills/variants/WaveStrike/TidalWaveEffect.js": 18146,
    "js/utils/CharacterModelPool.js": 6803,
    "js/utils/EnemyObjectPool.js": 6600,
    "js/game/Game.js": 29915,
    "js/game/GameEvents.js": 1148,
    "js/game/GameState.js": 1314,
    "js/game/LoadingManager.js": 1599,
    "js/game/SceneOptimizer.js": 4564,
    "js/hud-manager/DeathScreenUI.js": 1852,
    "js/hud-manager/DialogUI.js": 1843,
    "js/hud-manager/EnemyUI.js": 1842,
    "js/hud-manager/HUDManager.js": 14220,
    "js/hud-manager/HomeUI.js": 4118,
    "js/hud-manager/InventoryButton.js": 1863,
    "js/hud-manager/InventoryUI.js": 12891,
    "js/hud-manager/MiniMapButton.js": 2061,
    "js/hud-manager/MiniMapUI.js": 50767,
    "js/hud-manager/NotificationsUI.js": 18719,
    "js/hud-manager/PlayerUI.js": 3867,
    "js/hud-manager/QuestLogUI.js": 2709,
    "js/hud-manager/SkillSelectionButton.js": 4380,
    "js/hud-manager/SkillSelectionUI.js": 29311,
    "js/hud-manager/SkillTreeButton.js": 1867,
    "js/hud-manager/SkillTreeUI.js": 26754,
    "js/hud-manager/SkillsUI.js": 8306,
    "js/hud-manager/VirtualJoystickUI.js": 6963,
    "js/menu-system/ControlsDisplay.js": 8526,
    "js/menu-system/EnemyPreview.js": 12359,
    "js/menu-system/GameMenu.js": 10279,
    "js/menu-system/IMenu.js": 836,
    "js/menu-system/MainBackground.js": 1811,
    "js/menu-system/MenuManager.js": 5412,
    "js/menu-system/ModelPreview.js": 16289,
    "js/menu-system/SettingsMenu.js": 7721,
    "js/menu-system/SkillPreview.js": 27837,
    "js/menu-system/settings-menu/AudioTab.js": 5895,
    "js/menu-system/settings-menu/CharacterModelTab.js": 23021,
    "js/menu-system/settings-menu/ControlsTab.js": 1223,
    "js/menu-system/settings-menu/EnemyPreviewTab.js": 13083,
    "js/menu-system/settings-menu/GameplayTab.js": 2608,
    "js/menu-system/settings-menu/PerformanceTab.js": 7216,
    "js/menu-system/settings-menu/ReleaseTab.js": 3832,
    "js/menu-system/settings-menu/SettingsTab.js": 1400,
    "js/menu-system/settings-menu/SkillsPreviewTab.js": 9141,
    "js/menu-system/settings-menu/index.js": 533,
    "js/save-manager/ISaveSystem.js": 1255,
    "js/save-manager/IStorageAdapter.js": 1060,
    "js/save-manager/LocalStorageAdapter.js": 1831,
    "js/save-manager/SaveManager.js": 17997,
    "js/save-manager/serializers/PlayerSerializer.js": 4913,
    "js/save-manager/serializers/QuestSerializer.js": 3791,
    "js/save-manager/serializers/SettingsSerializer.js": 3440,
    "js/save-manager/utils/SaveOperationProgress.js": 6226,
    "js/services/InteractionResultHandler.js": 3849,
    "js/types.js": 8276,
    "js/utils/AnimationUtils.js": 10899,
    "js/utils/SkillTreeUtils.js": 3141,
    "js/utils/debug-utils.js": 1168,
    "js/world/WorldManager.js": 25544,
    "js/world/environment/Bush.js": 1849,
    "js/world/environment/EnvironmentManager.js": 21042,
    "js/world/environment/Flower.js": 4019,
    "js/world/environment/FogManager.js": 11408,
    "js/world/environment/Rock.js": 4594,
    "js/world/environment/Tree.js": 4528,
    "js/world/interactive/BossSpawnPoint.js": 1470,
    "js/world/interactive/InteractiveObjectManager.js": 15160,
    "js/world/interactive/QuestMarker.js": 8876,
    "js/world/interactive/TreasureChest.js": 6117,
    "js/world/lighting/LightingManager.js": 6719,
    "js/world/structures/Bridge.js": 14934,
    "js/world/structures/Building.js": 15301,
    "js/world/structures/DarkSanctum.js": 5009,
    "js/world/structures/Mountain.js": 14043,
    "js/world/structures/Ruins.js": 5086,
    "js/world/structures/StructureManager.js": 26102,
    "js/world/structures/Tower.js": 16012,
    "js/world/structures/Village.js": 21869,
    "js/world/teleport/TeleportManager.js": 59764,
    "js/world/terrain/TerrainManager.js": 48019,
    "js/world/utils/EnvironmentObjectPool.js": 6903,
    "js/world/utils/ModelObjectPool.js": 4476,
    "js/world/utils/ObjectPool.js": 6825,
    "js/world/utils/RandomGenerator.js": 2214,
    "js/world/utils/TerrainChunkPool.js": 4878,
    "js/world/utils/TextureGenerator.js": 4292,
    "js/world/zones/ZoneManager.js": 13789,
    "images/home.jpg": 141566,
    "images/logo-192.png": 15541,
    "images/logo-192.svg": 345,
    "images/logo-512.png": 62939,
    "images/logo-512.svg": 347,
    "assets/audio/ally_dismiss.mp3": 3456,
    "assets/audio/ally_summon.mp3": 2688,
    "assets/audio/attack.mp3": 2688,
    "assets/audio/barrier_dissipate.mp3": 4224,
    "assets/audio/barrier_form.mp3": 3456,
    "assets/audio/battle_theme.mp3": 40320,
    "assets/audio/bell_fade.mp3": 4224,
    "assets/audio/bell_ring.mp3": 5952,
    "assets/audio/boss_death.mp3": 5952,
    "assets/audio/boss_theme.mp3": 40320,
    "assets/audio/button_click.mp3": 1152,
    "assets/audio/chest_open.mp3": 2688,
    "assets/audio/cyclone_strike.mp3": 3456,
    "assets/audio/door_open.mp3": 3456,
    "assets/audio/enemy_attack.mp3": 1920,
    "assets/audio/enemy_death.mp3": 3456,
    "assets/audio/enemy_hit.mp3": 1152,
    "assets/audio/exploding_palm.mp3": 3456,
    "assets/audio/fist_of_thunder.mp3": 2688,
    "assets/audio/inner_sanctuary.mp3": 4992,
    "assets/audio/inventory_open.mp3": 1920,
    "assets/audio/item_pickup.mp3": 1920,
    "assets/audio/level_up.mp3": 3456,
    "assets/audio/main_theme.mp3": 585978,
    "assets/audio/mark_applied.mp3": 2688,
    "assets/audio/massive_explosion.mp3": 4992,
    "assets/audio/mystic_ally.mp3": 4224,
    "assets/audio/player_death.mp3": 4224,
    "assets/audio/player_hit.mp3": 1920,
    "assets/audio/rapid_strike.mp3": 1920,
    "assets/audio/seven_sided_strike.mp3": 4224,
    "assets/audio/strike_complete.mp3": 2688,
    "assets/audio/thunder_echo.mp3": 3456,
    "assets/audio/thunder_strike.mp3": 1920,
    "assets/audio/water_dissipate.mp3": 3456,
    "assets/audio/water_impact.mp3": 1920,
    "assets/audio/wave_of_light.mp3": 4992,
    "assets/audio/wave_strike.mp3": 2688,
    "assets/audio/wind_dissipate.mp3": 3456,
    "assets/audio/wind_pull.mp3": 2688,
    "assets/effects/buddha.glb": 55000, // Updated size for compressed Draco model
    "assets/images/background.jpg": 465241,
    "assets/models/monk-v3.glb": 155292,
    "assets/models/monk.glb": 366580
  };

// Function to send progress updates to the client
function sendProgressUpdate(completed, total, currentFile, loadedBytes, totalBytes) {
  if (messagePort) {
    messagePort.postMessage({
      type: 'CACHE_PROGRESS',
      completed,
      total,
      currentFile,
      loadedBytes,
      totalBytes,
      totalSizeMB: TOTAL_CACHE_SIZE_MB
    });
  }
}

// Communication channel
let messagePort = null;

// Listen for messages from the client
self.addEventListener('message', event => {
  // Check if it's the initialization message with the port
  if (event.data && event.data.type === 'INIT_PORT') {
    messagePort = event.data.port;
    console.debug('Communication channel established with client');
  }
});

// Function to cache files with progress tracking
async function cacheFilesWithProgress(cache) {
  const total = ASSETS_TO_CACHE.length;
  let completed = 0;
  let loadedBytes = 0;
  
  // Process files sequentially to ensure accurate progress tracking
  for (const url of ASSETS_TO_CACHE) {
    try {
      // Get file size (or 0 if not available)
      const fileSize = FILE_SIZES[url] || 0;
      
      // Send progress update before starting the fetch
      sendProgressUpdate(completed, total, url, loadedBytes, TOTAL_CACHE_SIZE_BYTES);
      
      // Handle empty URL (root path) specially
      const fetchUrl = url === '' ? './' : url;
      
      // Fetch and cache the file with proper request
      const request = new Request(fetchUrl, { method: 'GET' });
      const response = await fetch(request);
      
      if (response.ok) {
        await cache.put(url, response.clone());
        completed++;
        loadedBytes += fileSize;
        
        // Send progress update after successful caching
        sendProgressUpdate(completed, total, url, loadedBytes, TOTAL_CACHE_SIZE_BYTES);
      } else {
        console.warn(`Failed to cache ${url}: ${response.status} ${response.statusText}`);
        // Still increment completed to keep progress moving
        completed++;
        sendProgressUpdate(completed, total, `Failed: ${url}`, loadedBytes, TOTAL_CACHE_SIZE_BYTES);
      }
    } catch (error) {
      console.error(`Error caching ${url}:`, error);
      // Still increment completed to keep progress moving
      completed++;
      sendProgressUpdate(completed, total, `Error: ${url}`, loadedBytes, TOTAL_CACHE_SIZE_BYTES);
    }
  }
  
  return completed;
}

// Install event - cache all static assets with progress tracking
self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE_KEY)
      .then(cache => {
        console.debug('Caching app assets with progress tracking');
        console.debug(`Total cache size: ${TOTAL_CACHE_SIZE_MB} MB with progress tracking`);
        return cacheFilesWithProgress(cache);
      })
      .then(completedCount => {
        console.debug(`Cached ${completedCount} files successfully`);
        return self.skipWaiting();
      })
      .catch(error => {
        console.error('Failed to cache assets:', error);
      })
  );
});

// Activate event - clean up old caches
self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys().then(cacheNames => {
      return Promise.all(
        cacheNames.filter(cacheName => {
          return cacheName.startsWith(CACHE_NAME) && cacheName !== CACHE_KEY;
        }).map(cacheName => {
          console.debug('Deleting old cache:', cacheName);
          return caches.delete(cacheName);
        })
      );
    }).then(() => {
      return self.clients.claim();
    })
  );
});

// Fetch event - serve from cache, fall back to network
self.addEventListener('fetch', event => {
  // Get the requested URL
  const requestUrl = new URL(event.request.url);
  
  // Handle root path specially
  const cacheKey = requestUrl.pathname === '/' ? '' : requestUrl.pathname;
  
  event.respondWith(
    caches.match(cacheKey)
      .then(response => {
        if (response) {
          return response;
        }
        return fetch(event.request);
      })
      .catch(error => {
        console.error('Fetch error:', error);
        // You could return a custom offline page here
      })
  );
});
