/**
 * Default locale (translations only, like JSON). Same shape as chapters-vi.js.
 * Used by chapter-quests.js for default display. Logic stays in chapter-quests.js.
 */

/** Boss names for chapters 6–100 (cycle). Index = chapter index % 8. */
const BOSS_EN = [
    'Guardian of Strife', 'Shadow of Doubt', 'Avatar of Greed', 'Spirit of Loneliness',
    'Mirror of the Self', 'Bog of Regret', 'Frozen Heart', 'Lord of Illusion',
];

/** Chapter quest text (title, description, lesson, area, bossName). Index matches CHAPTER_QUESTS. */
export const EN_ENTRIES = [
    // Ch 1–5
    { title: 'The Restless Village', area: 'The Restless Village', description: 'A village consumed by anger—disputes over land, old grudges. A Rage Beast has taken root and feeds on their anger. Calm the conflicts and face the beast so the village can find peace.', lesson: 'Anger burns the one who carries it.', bossName: 'Rage Beast' },
    { title: 'Forest of Doubt', area: 'Forest of Doubt', description: 'A dense, misty forest where travelers lose their way and their courage. Something whispers in the dark. Face the Doubt Serpent so the forest can be free of paralyzing fear.', lesson: 'Fear grows in silence.', bossName: 'Doubt Serpent' },
    { title: 'Mountain of Desire', area: 'Mountain of Desire', description: 'A mountain where treasure hunters are obsessed with gold and power. A Golden Titan guards the peak. Navigate temptations and face the Titan to learn that gratitude—not accumulation—brings peace.', lesson: 'Gratitude ends endless hunger.', bossName: 'Golden Titan' },
    { title: 'Desert of Loneliness', area: 'Desert of Loneliness', description: 'A vast desert where travelers feel cut off—no landmarks, no companions. An Echo Phantom amplifies loneliness. Endure the emptiness, find connection, then face the Phantom.', lesson: 'You are never truly alone.', bossName: 'Echo Phantom' },
    { title: 'Inner Temple', area: 'Inner Temple', description: 'The final trial. Here the test is not an external monster but the self. A Shadow Self mirrors your skills and choices. Face this reflection and transcend the untrained self to earn Enlightenment Mode.', lesson: 'Your greatest opponent is your untrained self.', bossName: 'Shadow Self' },
    // Ch 6–100 (BOSS_EN cycle for bossName)
    { title: 'Valley of Patience', area: 'Valley of Patience', description: 'A valley where farmers have forgotten that growth takes time. A Guardian of Strife feeds on their impatience. Help them wait with kindness and face the guardian.', lesson: 'A jug fills drop by drop.', bossName: BOSS_EN[0] },
    { title: 'Meadow of the Present', area: 'Meadow of the Present', description: 'A meadow where spirits are trapped in yesterday. A Shadow of Doubt keeps them from seeing today. Free them by facing the shadow and living in the now.', lesson: 'Do not dwell in the past; concentrate on the present.', bossName: BOSS_EN[1] },
    { title: 'Village of Open Hands', area: 'Village of Open Hands', description: 'A village that hoards its harvest. An Avatar of Greed guards the granary. Teach sharing by example and defeat the avatar so all may eat.', lesson: 'Happiness never decreases by being shared.', bossName: BOSS_EN[2] },
    { title: 'Hollow of Echoes', area: 'Hollow of Echoes', description: 'A hollow where travelers hear only their own echoes. A Spirit of Loneliness amplifies isolation. Find connection and face the spirit so the hollow can sing again.', lesson: 'You are never truly alone.', bossName: BOSS_EN[3] },
    { title: 'Shrine of Self', area: 'Shrine of Self', description: 'A shrine where monks are tested by their own reflection. A Mirror of the Self blocks the path. Master your impulses and face the mirror.', lesson: 'Conquer yourself rather than a thousand battles.', bossName: BOSS_EN[4] },
    { title: 'Bog of Restlessness', area: 'Bog of Restlessness', description: 'A bog where no one can sit still. A Bog of Regret stirs the waters. Bring calm and face the creature so the bog may find stillness.', lesson: 'Peace comes from within.', bossName: BOSS_EN[5] },
    { title: 'Frost Garden', area: 'Frost Garden', description: 'A garden frozen by negative thoughts. A Frozen Heart guards the gate. Warm the minds of the gardeners and melt the heart.', lesson: 'The mind is everything; what you think, you become.', bossName: BOSS_EN[6] },
    { title: 'Ruin of Grudges', area: 'Ruin of Grudges', description: 'Ruins where old hatreds still burn. A Lord of Illusion feeds on revenge. Break the cycle with compassion and face the lord.', lesson: 'Hatred does not cease by hatred; only by love.', bossName: BOSS_EN[7] },
    { title: 'Path of Wanderers', area: 'Path of Wanderers', description: 'A path where travelers rush and miss the journey. A Guardian of Strife pushes them onward. Teach mindfulness and calm the guardian.', lesson: 'As you walk and eat and travel, be where you are.', bossName: BOSS_EN[0] },
    { title: 'Garden of Compassion', area: 'Garden of Compassion', description: 'A garden where kindness has withered. A Shadow of Doubt whispers that others are unworthy. Restore compassion and face the shadow.', lesson: 'Cultivate an unbounded heart toward all beings.', bossName: BOSS_EN[1] },
    { title: 'Cliff of Clinging', area: 'Cliff of Clinging', description: 'A cliff where people cling to broken things. An Avatar of Greed hoards the past. Help them release and defeat the avatar.', lesson: 'Let go of what no longer serves you.', bossName: BOSS_EN[2] },
    { title: 'Vale of Whispers', area: 'Vale of Whispers', description: 'A vale where harsh words have left scars. A Spirit of Loneliness echoes every insult. Speak with care and silence the spirit.', lesson: 'Words have the power to heal or harm.', bossName: BOSS_EN[3] },
    { title: 'Hamlet of Small Gifts', area: 'Hamlet of Small Gifts', description: 'A hamlet that believes only big deeds matter. A Mirror of the Self shows their neglect. Prove that small steps count and face the mirror.', lesson: 'Small acts of kindness change the world.', bossName: BOSS_EN[4] },
    { title: 'Marsh of Impatience', area: 'Marsh of Impatience', description: 'A marsh where everyone hurries and stumbles. A Bog of Regret thrives on haste. Slow down, help others slow down, and calm the bog.', lesson: 'Patience is the greatest virtue.', bossName: BOSS_EN[5] },
    { title: 'Cave of Judgement', area: 'Cave of Judgement', description: 'A cave where people see only faults. A Frozen Heart freezes every glance. Learn to see goodness and melt the heart.', lesson: 'See the light in others.', bossName: BOSS_EN[6] },
    { title: 'Mirage Desert', area: 'Mirage Desert', description: 'A desert of mirages and false hopes. A Lord of Illusion rules the dunes. See through the lies and defeat the lord.', lesson: 'Illusion fades when you look with clear eyes.', bossName: BOSS_EN[7] },
    { title: 'Slope of Haste', area: 'Slope of Haste', description: 'A slope where runners fall from rushing. A Guardian of Strife rewards speed over care. Show that steady steps reach the top and face the guardian.', lesson: 'Steady effort wins the race.', bossName: BOSS_EN[0] },
    { title: 'Clock Tower Ruins', area: 'Clock Tower Ruins', description: 'Ruins where everyone lives in past or future. A Shadow of Doubt lives in the clock. Bring them to the now and silence the shadow.', lesson: 'The present moment is the only moment.', bossName: BOSS_EN[1] },
    { title: 'Granary of the Miser', area: 'Granary of the Miser', description: 'A granary full of grain that no one shares. An Avatar of Greed guards the door. Open the granary with generosity and defeat the avatar.', lesson: 'Generosity multiplies what you have.', bossName: BOSS_EN[2] },
    { title: 'Lonely Lighthouse', area: 'Lonely Lighthouse', description: 'A lighthouse where the keeper has forgotten others. A Spirit of Loneliness dims the light. Reconnect the keeper to the world and face the spirit.', lesson: 'Connection heals the soul.', bossName: BOSS_EN[3] },
    { title: 'Crossroads of Fate', area: 'Crossroads of Fate', description: 'A crossroads where choices were made in fear. A Mirror of the Self shows the cost. Choose with wisdom and face the mirror.', lesson: 'Your choices shape who you become.', bossName: BOSS_EN[4] },
    { title: 'Restless Pond', area: 'Restless Pond', description: 'A pond that never stills; no one sees their reflection. A Bog of Regret churns the water. Bring stillness and calm the bog.', lesson: 'Still water reflects the sky.', bossName: BOSS_EN[5] },
    { title: 'Ice Temple', area: 'Ice Temple', description: 'A temple frozen by indifference. A Frozen Heart sits on the altar. Bring warmth and compassion to melt the heart.', lesson: 'Warmth melts the coldest heart.', bossName: BOSS_EN[6] },
    { title: 'Hall of Mirrors', area: 'Hall of Mirrors', description: 'A hall where illusions flatter and deceive. A Lord of Illusion rules. See the truth and shatter the lord.', lesson: 'Reality is kinder than illusion.', bossName: BOSS_EN[7] },
    { title: 'Summit of Impatience', area: 'Summit of Impatience', description: 'A mountain where climbers quit too soon. A Guardian of Strife mocks their effort. Persist step by step and face the guardian.', lesson: 'One step at a time reaches the mountain.', bossName: BOSS_EN[0] },
    { title: "Yesterday's Garden", area: "Yesterday's Garden", description: 'A garden stuck in memory. A Shadow of Doubt lives in the past. Plant seeds for today and quiet the shadow.', lesson: 'Today is the day that matters.', bossName: BOSS_EN[1] },
    { title: 'Market of Closed Fists', area: 'Market of Closed Fists', description: 'A market where no one trades. An Avatar of Greed keeps the stalls locked. Open hands open hearts; defeat the avatar.', lesson: 'Sharing fills both hands.', bossName: BOSS_EN[2] },
    { title: 'Divided Valley', area: 'Divided Valley', description: 'A valley split by old disputes. A Spirit of Loneliness keeps the sides apart. Bridge the divide and face the spirit.', lesson: 'Together we are stronger.', bossName: BOSS_EN[3] },
    { title: 'Dojo of Ego', area: 'Dojo of Ego', description: 'A dojo where students fight for glory. A Mirror of the Self shows their pride. Humble the ego and face the mirror.', lesson: 'Master the self before mastering others.', bossName: BOSS_EN[4] },
    { title: 'Rapids of Anger', area: 'Rapids of Anger', description: 'Rapids where anger churns the water. A Bog of Regret feeds on rage. Bring calm and still the bog.', lesson: 'Calm waters run deep.', bossName: BOSS_EN[5] },
    { title: 'Wasteland of Scorn', area: 'Wasteland of Scorn', description: 'A wasteland where kindness was mocked. A Frozen Heart rules. Sow kindness and melt the heart.', lesson: 'Kindness is never wasted.', bossName: BOSS_EN[6] },
    { title: 'Labyrinth of Lies', area: 'Labyrinth of Lies', description: 'A labyrinth built on lies. A Lord of Illusion guards the center. Speak truth and defeat the lord.', lesson: 'Truth is the first step to freedom.', bossName: BOSS_EN[7] },
    { title: 'Beach of Hurry', area: 'Beach of Hurry', description: 'A beach where no one waits for the tide. A Guardian of Strife rushes everyone. Teach patience and face the guardian.', lesson: 'Patience turns sand into pearl.', bossName: BOSS_EN[0] },
    { title: 'Inn of Tomorrow', area: 'Inn of Tomorrow', description: 'An inn where guests only plan for tomorrow. A Shadow of Doubt lives in their plans. Live in the now and quiet the shadow.', lesson: 'The now is your only home.', bossName: BOSS_EN[1] },
    { title: 'Temple of Tithes', area: 'Temple of Tithes', description: 'A temple that demands payment for every blessing. An Avatar of Greed counts every coin. Give freely and defeat the avatar.', lesson: 'Give without expecting return.', bossName: BOSS_EN[2] },
    { title: 'Isle of Indifference', area: 'Isle of Indifference', description: 'An isle where no one helps another. A Spirit of Loneliness thrives. Extend a hand and face the spirit.', lesson: 'A friend in need is a friend indeed.', bossName: BOSS_EN[3] },
    { title: 'Shrine of Sleep', area: 'Shrine of Sleep', description: 'A shrine where no one looks inward. A Mirror of the Self waits. Examine yourself and face the mirror.', lesson: 'The unexamined life is not worth living.', bossName: BOSS_EN[4] },
    { title: 'Bazaar of Noise', area: 'Bazaar of Noise', description: 'A bazaar so loud no one hears themselves. A Bog of Regret adds to the din. Find stillness and calm the bog.', lesson: 'Stillness reveals what noise hides.', bossName: BOSS_EN[5] },
    { title: 'Snowfield of Solitude', area: 'Snowfield of Solitude', description: 'A snowfield where everyone is alone. A Frozen Heart keeps the cold. Bring love and melt the heart.', lesson: 'Love thaws the coldest winter.', bossName: BOSS_EN[6] },
    { title: 'Fog of Dread', area: 'Fog of Dread', description: 'A fog that fear makes thick. A Lord of Illusion feeds on dread. Walk with courage and disperse the lord.', lesson: 'See through the veil of fear.', bossName: BOSS_EN[7] },
    { title: 'Race of Haste', area: 'Race of Haste', description: 'A race where everyone trips from speed. A Guardian of Strife cheers the reckless. Run with care and face the guardian.', lesson: 'Slow and steady wins.', bossName: BOSS_EN[0] },
    { title: 'Graveyard of Grudges', area: 'Graveyard of Grudges', description: 'A graveyard where grudges are still tended. A Shadow of Doubt tends the plots. Let the dead rest and quiet the shadow.', lesson: 'Let the past rest.', bossName: BOSS_EN[1] },
    { title: 'Vault of the Hoarder', area: 'Vault of the Hoarder', description: 'A vault full of gold no one uses. An Avatar of Greed sleeps on the pile. Share the wealth and defeat the avatar.', lesson: 'Wealth shared is wealth doubled.', bossName: BOSS_EN[2] },
    { title: 'Archipelago of Pride', area: 'Archipelago of Pride', description: 'Islands that refuse to build bridges. A Spirit of Loneliness rules the straits. Connect the islands and face the spirit.', lesson: 'No one is an island.', bossName: BOSS_EN[3] },
    { title: 'Arena of Rage', area: 'Arena of Rage', description: 'An arena where fighters lose themselves to anger. A Mirror of the Self reflects their fury. Find control and face the mirror.', lesson: 'True strength is self-control.', bossName: BOSS_EN[4] },
    { title: 'Cacophony Canyon', area: 'Cacophony Canyon', description: 'A canyon of endless noise. A Bog of Regret amplifies every sound. Find silence and calm the bog.', lesson: 'Quiet the mind to hear the heart.', bossName: BOSS_EN[5] },
    { title: 'Fortress of Fear', area: 'Fortress of Fear', description: 'A fortress built by fear. A Frozen Heart guards the gate. Approach with compassion and melt the heart.', lesson: 'Compassion is courage.', bossName: BOSS_EN[6] },
    { title: 'Masquerade Hall', area: 'Masquerade Hall', description: 'A hall where everyone wears masks. A Lord of Illusion loves the disguise. Remove the masks and defeat the lord.', lesson: 'Reality needs no disguise.', bossName: BOSS_EN[7] },
    { title: 'Threshold of Doubt', area: 'Threshold of Doubt', description: 'A threshold no one dares to cross. A Guardian of Strife blocks the way. Take the first step and face the guardian.', lesson: 'Every journey begins with one step.', bossName: BOSS_EN[0] },
    { title: 'Asthma of Anxiety', area: 'Asthma of Anxiety', description: 'A place where worry steals every breath. A Shadow of Doubt whispers what-ifs. Breathe in the now and quiet the shadow.', lesson: "Today's breath is today's gift.", bossName: BOSS_EN[1] },
    { title: 'Well of Want', area: 'Well of Want', description: 'A well that runs dry from hoarding. An Avatar of Greed guards the bucket. Give first and defeat the avatar.', lesson: 'The more you give, the more you have.', bossName: BOSS_EN[2] },
    { title: 'Darkness of Division', area: 'Darkness of Division', description: 'A place divided by suspicion. A Spirit of Loneliness darkens every corner. Unite and light the way; face the spirit.', lesson: 'Unity makes light.', bossName: BOSS_EN[3] },
    { title: 'Maze of Mirrors', area: 'Maze of Mirrors', description: 'A maze of reflections. A Mirror of the Self hides the exit. Know who you are and face the mirror.', lesson: 'Know thyself.', bossName: BOSS_EN[4] },
    { title: 'War Camp', area: 'War Camp', description: 'A camp where war never ends. A Bog of Regret fuels the fights. Practice peace and calm the bog.', lesson: 'Peace is a practice.', bossName: BOSS_EN[5] },
    { title: 'Toll Bridge', area: 'Toll Bridge', description: 'A bridge where every crossing has a price. A Frozen Heart collects the toll. Offer kindness instead and melt the heart.', lesson: 'Kindness costs nothing.', bossName: BOSS_EN[6] },
    { title: 'Prison of Pretense', area: 'Prison of Pretense', description: 'A prison built on pretense. A Lord of Illusion is the warden. Speak truth and break free; defeat the lord.', lesson: 'Truth sets you free.', bossName: BOSS_EN[7] },
    { title: 'Harvest of Haste', area: 'Harvest of Haste', description: 'A harvest ruined by picking too soon. A Guardian of Strife urges speed. Wait for ripeness and face the guardian.', lesson: 'Wait for the right moment.', bossName: BOSS_EN[0] },
    { title: 'Dungeon of Memory', area: 'Dungeon of Memory', description: 'A dungeon where the past chains the present. A Shadow of Doubt holds the keys. Learn and let go; quiet the shadow.', lesson: 'The past is a teacher, not a prison.', bossName: BOSS_EN[1] },
    { title: 'Counting House', area: 'Counting House', description: 'A house where every gift is counted. An Avatar of Greed keeps the ledger. Give without counting and defeat the avatar.', lesson: 'Give from the heart.', bossName: BOSS_EN[2] },
    { title: "Hermit's Peak", area: "Hermit's Peak", description: 'A peak where a hermit has forgotten others. A Spirit of Loneliness lives in the cave. Remind the hermit of connection and face the spirit.', lesson: 'We need each other.', bossName: BOSS_EN[3] },
    { title: 'Gate of Arrogance', area: 'Gate of Arrogance', description: 'A gate that pride has locked. A Mirror of the Self guards it. Approach with humility and face the mirror.', lesson: 'Humility opens doors.', bossName: BOSS_EN[4] },
    { title: 'Tower of Tongues', area: 'Tower of Tongues', description: 'A tower where no one stops talking. A Bog of Regret adds to the noise. Embrace silence and calm the bog.', lesson: 'Silence speaks.', bossName: BOSS_EN[5] },
    { title: 'Wall of Strangers', area: 'Wall of Strangers', description: 'A wall that separates neighbors. A Frozen Heart built it. Tear it down with love and melt the heart.', lesson: 'Love your neighbor as yourself.', bossName: BOSS_EN[6] },
    { title: 'Feast of Phantoms', area: 'Feast of Phantoms', description: 'A feast that looks real but leaves everyone hungry. A Lord of Illusion serves the plates. Seek real nourishment and defeat the lord.', lesson: 'Illusion cannot feed the hungry.', bossName: BOSS_EN[7] },
    { title: 'Quarry of Quitters', area: 'Quarry of Quitters', description: 'A quarry abandoned too soon. A Guardian of Strife mocks the workers. Return and persevere; face the guardian.', lesson: 'Perseverance moves mountains.', bossName: BOSS_EN[0] },
    { title: 'Waiting Room', area: 'Waiting Room', description: 'A room where everyone waits for someday. A Shadow of Doubt says "not yet." Act now and quiet the shadow.', lesson: 'Now is the time.', bossName: BOSS_EN[1] },
    { title: 'Dam of Greed', area: 'Dam of Greed', description: 'A dam that holds back the river of plenty. An Avatar of Greed controls the gates. Open the gates and defeat the avatar.', lesson: 'Abundance flows when shared.', bossName: BOSS_EN[2] },
    { title: 'Pit of Division', area: 'Pit of Division', description: 'A pit where divided people fall. A Spirit of Loneliness deepens the pit. Unite and climb; face the spirit.', lesson: 'Together we rise.', bossName: BOSS_EN[3] },
    { title: 'Throne of Impulse', area: 'Throne of Impulse', description: 'A throne where impulse rules. A Mirror of the Self sits there. Rule yourself and face the mirror.', lesson: 'The wise rule themselves.', bossName: BOSS_EN[4] },
    { title: 'Battlefield of Nerves', area: 'Battlefield of Nerves', description: 'A battlefield of anxious thoughts. A Bog of Regret fuels the war. Find inner peace and calm the bog.', lesson: 'Inner peace, outer peace.', bossName: BOSS_EN[5] },
    { title: 'Frostbite Fields', area: 'Frostbite Fields', description: 'Fields where cold has spread from cold hearts. A Frozen Heart rules. Bring warmth and melt the heart.', lesson: 'Warmth begets warmth.', bossName: BOSS_EN[6] },
    { title: 'Dream Palace', area: 'Dream Palace', description: 'A palace built on dreams that ignore reality. A Lord of Illusion decorates the halls. Wake up and defeat the lord.', lesson: 'Face what is real.', bossName: BOSS_EN[7] },
    { title: 'Panting Peak', area: 'Panting Peak', description: 'A peak where climbers gasp and give up. A Guardian of Strife pushes too hard. Breathe, step, and face the guardian.', lesson: 'One breath, one step.', bossName: BOSS_EN[0] },
    { title: 'River of Regret', area: 'River of Regret', description: 'A river that runs backward into the past. A Shadow of Doubt swims in it. Let the river flow forward and quiet the shadow.', lesson: 'Release what you cannot change.', bossName: BOSS_EN[1] },
    { title: 'Chain of Possession', area: 'Chain of Possession', description: 'A chain of attachments. An Avatar of Greed forges the links. Release and give; defeat the avatar.', lesson: 'Generosity is freedom.', bossName: BOSS_EN[2] },
    { title: 'Web of Strangers', area: 'Web of Strangers', description: 'A web where each thread is alone. A Spirit of Loneliness weaves it. Connect the threads and face the spirit.', lesson: 'We are all connected.', bossName: BOSS_EN[3] },
    { title: 'Chaos Monastery', area: 'Chaos Monastery', description: 'A monastery where minds run wild. A Mirror of the Self multiplies the chaos. Master your mind and face the mirror.', lesson: 'Master the mind.', bossName: BOSS_EN[4] },
    { title: 'Whirlwind Plaza', area: 'Whirlwind Plaza', description: 'A plaza of constant motion. A Bog of Regret spins in the center. Find stillness within and calm the bog.', lesson: 'Stillness in motion.', bossName: BOSS_EN[5] },
    { title: 'Den of Dread', area: 'Den of Dread', description: 'A den where fear has made its home. A Frozen Heart feeds the dread. Enter with compassion and melt the heart.', lesson: 'Compassion conquers fear.', bossName: BOSS_EN[6] },
    { title: 'Gilded Cave', area: 'Gilded Cave', description: 'A cave covered in false gold. A Lord of Illusion paints the walls. See the real and defeat the lord.', lesson: 'Strip away the false.', bossName: BOSS_EN[7] },
    { title: 'Marathon of Despair', area: 'Marathon of Despair', description: 'A marathon that breaks the spirit. A Guardian of Strife runs beside you. Endure and finish; face the guardian.', lesson: 'Endurance wins.', bossName: BOSS_EN[0] },
    { title: 'Palace of More', area: 'Palace of More', description: 'A palace where more is never enough. A Shadow of Doubt lives in the vaults. Find enough in the now and quiet the shadow.', lesson: 'This moment is enough.', bossName: BOSS_EN[1] },
    { title: 'Solo Path', area: 'Solo Path', description: 'A path meant for many, walked by one. An Avatar of Greed took the rest. Share the path and defeat the avatar.', lesson: 'Share the journey.', bossName: BOSS_EN[2] },
    { title: 'Sickbed Isle', area: 'Sickbed Isle', description: 'An isle of the sick who refuse help. A Spirit of Loneliness tends them. Offer healing and face the spirit.', lesson: 'No one heals alone.', bossName: BOSS_EN[3] },
    { title: 'Victory Arch', area: 'Victory Arch', description: 'An arch that celebrates the self. A Mirror of the Self stands under it. Lay down the crown and face the mirror.', lesson: 'Ego is the only enemy.', bossName: BOSS_EN[4] },
    { title: 'Noise Tower', area: 'Noise Tower', description: 'A tower where thoughts never stop. A Bog of Regret adds to the clamor. Quiet the mind and calm the bog.', lesson: 'Quiet mind, clear path.', bossName: BOSS_EN[5] },
    { title: 'Border Fort', area: 'Border Fort', description: 'A fort that keeps others out. A Frozen Heart holds the keys. Open the gate with love and melt the heart.', lesson: 'Love crosses every border.', bossName: BOSS_EN[6] },
    { title: 'Armory of Lies', area: 'Armory of Lies', description: 'An armory that arms with lies. A Lord of Illusion polishes the weapons. Disarm with truth and defeat the lord.', lesson: 'Truth needs no armor.', bossName: BOSS_EN[7] },
    { title: 'Sprint Valley', area: 'Sprint Valley', description: 'A valley where everyone sprints and falls. A Guardian of Strife rewards the fastest. Walk with patience and face the guardian.', lesson: 'Patience is strength.', bossName: BOSS_EN[0] },
    { title: 'Scriptorium of Fate', area: 'Scriptorium of Fate', description: 'A scriptorium where fate is written in stone. A Shadow of Doubt holds the quill. Rewrite with hope and quiet the shadow.', lesson: 'The future is unwritten.', bossName: BOSS_EN[1] },
    { title: 'Fist Treasury', area: 'Fist Treasury', description: 'A treasury held in closed fists. An Avatar of Greed pries them open. Open your hands and defeat the avatar.', lesson: 'Open hands receive more.', bossName: BOSS_EN[2] },
    { title: 'Storm of Solitude', area: 'Storm of Solitude', description: 'A storm that isolates everyone. A Spirit of Loneliness rides the wind. Build shelter together and face the spirit.', lesson: 'Community is shelter.', bossName: BOSS_EN[3] },
    { title: 'Colosseum of Conquest', area: 'Colosseum of Conquest', description: 'A colosseum that glorifies conquest. A Mirror of the Self awards the crown. Conquer yourself and face the mirror.', lesson: 'The greatest victory is over oneself.', bossName: BOSS_EN[4] },
    { title: 'Ash of Defeat', area: 'Ash of Defeat', description: 'Ashes of past failures. A Bog of Regret stirs them. Breathe and begin again; calm the bog.', lesson: 'Breathe and begin again.', bossName: BOSS_EN[5] },
    { title: 'Stairway of Scorn', area: 'Stairway of Scorn', description: 'Stairs where every step is scorn. A Frozen Heart built them. Climb with kindness and melt the heart.', lesson: 'Kindness is the first step.', bossName: BOSS_EN[6] },
    { title: 'Mirage Oasis', area: 'Mirage Oasis', description: 'An oasis that is only a mirage. A Lord of Illusion tends the illusion. Seek real water and defeat the lord.', lesson: 'Reality is enough.', bossName: BOSS_EN[7] },
    { title: 'Leap Canyon', area: 'Leap Canyon', description: 'A canyon no one can leap. A Guardian of Strife dares them to try. Cross step by step and face the guardian.', lesson: 'Step by step, the path is walked.', bossName: BOSS_EN[0] },
    { title: "Tomorrow's Store", area: "Tomorrow's Store", description: "A store that only sells tomorrow. A Shadow of Doubt runs the counter. Accept today's gift and quiet the shadow.", lesson: 'Today is the gift.', bossName: BOSS_EN[1] },
    { title: 'Pit of Competition', area: 'Pit of Competition', description: 'A pit where everyone climbs over others. An Avatar of Greed stands at the top. Lift each other and defeat the avatar.', lesson: 'We rise by lifting others.', bossName: BOSS_EN[2] },
    { title: 'Hospital of Walls', area: 'Hospital of Walls', description: 'A hospital where no one visits. A Spirit of Loneliness walks the halls. Visit and heal together; face the spirit.', lesson: 'Healing is mutual.', bossName: BOSS_EN[3] },
    { title: 'Throne of Blame', area: 'Throne of Blame', description: 'A throne from which everyone blames others. A Mirror of the Self reflects the finger. Know yourself and face the mirror.', lesson: 'True power is self-knowledge.', bossName: BOSS_EN[4] },
    { title: 'Parliament of Noise', area: 'Parliament of Noise', description: 'A parliament where no one listens. A Bog of Regret shouts the loudest. Listen in silence and calm the bog.', lesson: 'In silence, wisdom speaks.', bossName: BOSS_EN[5] },
    { title: 'Chasm of Contempt', area: 'Chasm of Contempt', description: 'A chasm between us and them. A Frozen Heart widens it. Build a bridge of compassion and melt the heart.', lesson: 'Compassion is the bridge.', bossName: BOSS_EN[6] },
    { title: 'Stage of Illusion', area: 'Stage of Illusion', description: 'A stage where illusion is the show. A Lord of Illusion takes the bow. Let the curtain fall and defeat the lord.', lesson: 'Illusion fades; truth remains.', bossName: BOSS_EN[7] },
    { title: 'Mountain of Overwhelm', area: 'Mountain of Overwhelm', description: 'A mountain that overwhelms every climber. A Guardian of Strife points at the peak. Take one step and face the guardian.', lesson: 'The path is walked one step at a time.', bossName: BOSS_EN[0] },
    { title: 'Nomad Camp', area: 'Nomad Camp', description: 'A camp of nomads who never rest in the now. A Shadow of Doubt keeps them moving. Rest in the present and quiet the shadow.', lesson: 'The present is your home.', bossName: BOSS_EN[1] },
    { title: 'Famine of Hoarding', area: 'Famine of Hoarding', description: 'A land of famine beside full storehouses. An Avatar of Greed locks the doors. Share and defeat the avatar.', lesson: 'To have enough, share.', bossName: BOSS_EN[2] },
    { title: 'Tribe of Enemies', area: 'Tribe of Enemies', description: 'A tribe split into enemies. A Spirit of Loneliness sharpens the knives. Remember you are family and face the spirit.', lesson: 'We are one family.', bossName: BOSS_EN[3] },
    { title: 'Final Gate', area: 'Final Gate', description: 'The final gate before mastery. A Mirror of the Self is the last guardian. Transcend the untrained self and face the mirror to earn the Path of Mastery.', lesson: 'The untrained self is the only foe.', bossName: BOSS_EN[4] },
];

/** Reflection screen UI. */
export const reflectionUi = {
    continueJourney: 'Continue Journey',
    enterPathOfMastery: 'Enter Path of Mastery',
    reflectionQuestionPrompt: 'What did you notice?',
    reflectionOption1: 'The struggle—and the chance to help.',
    reflectionOption2: 'The calm that followed the storm.',
    reflectionOption3: 'Both: action and peace together.',
};

/** Quest messages UI. Placeholders: {label}, {current}, {count}, etc. */
export const questUi = {
    travelToGetNextQuest: 'Travel to "{label}" to get your next quest.',
    storyQuestAvailable: 'A story quest is available. Look for the quest log on the left.',
    journeyHint: 'Your journey: complete the objectives in the quest log, then face the chapter boss.',
    questProgressCount: 'Quest: {current}/{count} {type}',
    questProgressEnemiesDefeated: 'Quest progress: {current}/{count} enemies defeated',
    questProgressFound: 'Quest progress: {current}/{count} {objectType}s found',
    zoneDiscovered: 'Zone discovered: {zoneName}',
    questCompletedTitle: 'Quest Completed: {title}',
    questCompletedRewards: 'You have completed the quest and received your rewards!',
    newQuestAvailable: 'New Quest Available: {name}',
    newQuestAtLevel: 'New quest "{name}" will be available at level {level}.',
    acceptQuestPrompt: 'Would you like to accept this quest?',
    newQuestTitle: 'New Quest: {title}',
    newMainQuestAvailable: 'New Main Quest Available: {name}',
    newSideQuestAvailable: 'New Side Quest Available: {name}',
    gainedExperience: 'Gained {xp} experience',
    gainedSkillPoints: 'Gained {count} skill point(s)',
    gainedGold: 'Gained {gold} gold',
    equipped: 'Equipped {itemName}',
    received: 'Received {itemName} x{amount}',
    enemies: 'enemies',
    boss: 'boss',
    nextMapFallback: 'the next map',
    otherPathsAvailable: 'Other paths await in the Story panel.',
    choiceInQuestHint: 'You can help in more than one way; complete at least one path to progress.',
    choiceCallout: 'Choice',
    storyQuestAwaitsOnMap: 'A story quest awaits. Find the quest marker on the map (marked with !) to begin.',
    findQuestMarkerHint: '→ Find the quest marker (yellow ! on the map) to start your journey.',
    noActiveQuests: 'No active quests',
    reviewMore: 'Review more ({count})',
    showLess: 'Show less',
    activeQuestsTitle: 'Active Quests',
    lessonLabel: 'Lesson',
    close: 'Close',
};

/** Map selection overlay UI. */
export const mapSelectionUi = {
    selectMapTitle: 'Select Map',
    currentMap: 'Current: {name}',
    currentMapNone: 'Current: —',
    returnToDefaultWorld: 'Returned to Default World.',
    mapSetToReloading: 'Map set to "{mapName}". Reloading...',
    selectMapPlaceholder: 'Select a map',
    chooseMapPlaceholder: 'Choose a map from the list to view details',
    statSize: 'Size:',
    statStructures: 'Structures:',
    statPaths: 'Paths:',
    statEnvironment: 'Environment:',
    statEnemies: 'Enemies:',
    enemiesRandom: 'Random',
    btnMapSelector: 'Map Selector',
    btnReturnToProceduralWorld: 'Return to Procedural World',
    btnGenerateNewMap: 'Generate New Map',
    btnSaveAndClose: 'Save & Close',
    btnApplyAndReload: 'Teleport',
    btnApplyAndReloadTitle: 'Teleport to this map',
    arrivedAtMap: 'You have arrived at {mapName}.',
    teleporting: 'Teleporting…',
    loadingMap: 'Loading map...',
    teleportToOriginTitle: 'Teleport to Origin',
    btnStoryBook: 'Story',
    storyBookTitle: 'The Journey',
    storyChapterLabel: 'Chapter {n}',
    storyPrevChapter: '‹ Previous',
    storyNextChapter: 'Next ›',
    storyCloseBook: 'Close',
    storySaveBook: 'Save',
    storySaveBookEmoji: '💾',
    storyVuongLamLabel: 'Tale of Vương Lâm (Renegade Immortal)',
    storyNoLongStory: 'No long story for this chapter.',
    storyChaptersBtn: 'Chapters',
    storyChaptersPanelTitle: 'Jump to chapter',
};
