/**
 * Vietnamese short quest text for chapters 1–100 (title, description, lesson, area, bossName).
 * EN comes from chapter-quests.js; VI is this single file.
 * @type {{ title: string, description: string, lesson: string, area: string, bossName?: string }[]}
 */
export const VI_ENTRIES = [
    // Ch 1–5
    { title: 'Làng Bất An', area: 'Làng Bất An', description: 'Một ngôi làng chìm trong sự giận dữ—tranh chấp đất đai, thù hận cũ. Một Con Thú Giận Dữ đã bám rễ và ăn sự tức giận của họ. Hãy xoa dịu xung đột và đối mặt con thú để làng tìm được bình yên.', lesson: 'Sự giận dữ đốt cháy chính kẻ mang nó.', bossName: 'Con Thú Giận Dữ' },
    { title: 'Rừng Nghi Ngờ', area: 'Rừng Nghi Ngờ', description: 'Một khu rừng rậm, sương mù nơi lữ khách lạc lối và mất can đảm. Có gì đó thì thầm trong bóng tối. Hãy đối mặt Rắn Nghi Ngờ để rừng thoát khỏi nỗi sợ tê liệt.', lesson: 'Sợ hãi lớn lên trong im lặng.', bossName: 'Rắn Nghi Ngờ' },
    { title: 'Núi Tham Vọng', area: 'Núi Tham Vọng', description: 'Ngọn núi nơi những kẻ săn báu bị ám ảnh bởi vàng và quyền lực. Một Titan Vàng canh giữ đỉnh. Vượt qua cám dỗ và đối mặt Titan để hiểu rằng lòng biết ơn—không phải tích lũy—mới mang lại bình yên.', lesson: 'Lòng biết ơn chấm dứt cơn đói vô tận.', bossName: 'Titan Vàng' },
    { title: 'Sa Mạc Cô Đơn', area: 'Sa Mạc Cô Đơn', description: 'Sa mạc mênh mông nơi lữ khách cảm thấy cô lập—không mốc, không bạn đồng hành. Một Bóng Ma Tiếng Vọng khuếch đại nỗi cô đơn. Chịu đựng sự trống rỗng, tìm sự kết nối, rồi đối mặt Bóng Ma.', lesson: 'Bạn không bao giờ thực sự cô đơn.', bossName: 'Bóng Ma Tiếng Vọng' },
    { title: 'Đền Nội Tâm', area: 'Đền Nội Tâm', description: 'Thử thách cuối cùng. Ở đây bài kiểm tra không phải quái vật bên ngoài mà là chính bản thân. Một Bóng Ta phản chiếu kỹ năng và lựa chọn của bạn. Đối mặt sự phản chiếu này và vượt qua bản thân chưa rèn luyện để đạt Chế Độ Giác Ngộ.', lesson: 'Đối thủ lớn nhất của bạn là bản thân chưa rèn luyện.', bossName: 'Bóng Ta' },
    // Ch 6–15
    { title: 'Thung Lũng Kiên Nhẫn', area: 'Thung Lũng Kiên Nhẫn', description: 'Thung lũng nơi nông dân quên rằng mọi thứ cần thời gian. Kẻ Canh Giữ Xung Đột ăn sự thiếu kiên nhẫn. Giúp họ chờ đợi bằng lòng tốt và đối mặt kẻ canh giữ.', lesson: 'Bình đầy từng giọt.' },
    { title: 'Đồng Cỏ Hiện Tại', area: 'Đồng Cỏ Hiện Tại', description: 'Đồng cỏ nơi linh hồn mắc kẹt trong quá khứ. Bóng Nghi Ngờ ngăn họ thấy hôm nay. Giải phóng họ bằng cách đối mặt bóng và sống trong hiện tại.', lesson: 'Đừng sống trong quá khứ; hãy tập trung vào hiện tại.' },
    { title: 'Làng Mở Lòng', area: 'Làng Mở Lòng', description: 'Làng tích trữ mùa màng. Hình Tượng Tham Lam canh vựa lúa. Dạy chia sẻ bằng hành động và đánh bại hình tượng để mọi người được ăn.', lesson: 'Hạnh phúc không giảm khi được chia sẻ.' },
    { title: 'Hõm Tiếng Vọng', area: 'Hõm Tiếng Vọng', description: 'Hõm nơi lữ khách chỉ nghe tiếng mình. Linh Hồn Cô Đơn khuếch đại sự cô lập. Tìm kết nối và đối mặt linh hồn để hõm lại cất tiếng.', lesson: 'Bạn không bao giờ thực sự cô đơn.' },
    { title: 'Đền Bản Thể', area: 'Đền Bản Thể', description: 'Đền nơi tăng nhân bị thử thách bởi chính bóng mình. Gương Bản Thể chặn lối. Làm chủ bản thân và đối mặt gương.', lesson: 'Chiến thắng chính mình hơn nghìn trận.' },
    { title: 'Bãi Lầy Bất An', area: 'Bãi Lầy Bất An', description: 'Bãi lầy nơi không ai ngồi yên. Bãi Lầy Hối Tiếc khuấy nước. Mang sự tĩnh lặng và đối mặt sinh vật để bãi lầy lặng.', lesson: 'Bình yên đến từ bên trong.' },
    { title: 'Vườn Băng Giá', area: 'Vườn Băng Giá', description: 'Vườn đóng băng vì suy nghĩ tiêu cực. Trái Tim Băng Giá canh cổng. Sưởi ấm tâm trí người làm vườn và làm tan trái tim.', lesson: 'Tâm trí là tất cả; bạn nghĩ gì, bạn thành vậy.' },
    { title: 'Tàn Tích Thù Hận', area: 'Tàn Tích Thù Hận', description: 'Tàn tích nơi thù hận cũ vẫn cháy. Chúa Ảo Ảnh ăn sự báo thù. Phá vòng luẩn quẩn bằng từ bi và đối mặt chúa tể.', lesson: 'Hận thù không chấm dứt bởi hận thù; chỉ bởi tình thương.' },
    { title: 'Đường Lữ Khách', area: 'Đường Lữ Khách', description: 'Con đường nơi lữ khách vội vã và bỏ lỡ hành trình. Kẻ Canh Giữ Xung Đột thúc họ. Dạy chánh niệm và làm dịu kẻ canh giữ.', lesson: 'Khi đi, ăn và đi, hãy có mặt nơi bạn đang ở.' },
    { title: 'Vườn Từ Bi', area: 'Vườn Từ Bi', description: 'Vườn nơi lòng tốt đã héo. Bóng Nghi Ngờ thì thầm rằng kẻ khác không đáng. Khôi phục từ bi và đối mặt bóng.', lesson: 'Tu dưỡng tấm lòng vô biên với chúng sinh.' },
    // Ch 16–25
    { title: 'Vách Núi Bám Víu', area: 'Vách Núi Bám Víu', description: 'Vách núi nơi người ta bám vào thứ đã vỡ. Hình Tượng Tham Lam tích trữ quá khứ. Giúp họ buông và đánh bại hình tượng.', lesson: 'Buông điều không còn phục vụ bạn.' },
    { title: 'Thung Lũng Thì Thầm', area: 'Thung Lũng Thì Thầm', description: 'Thung lũng nơi lời ác để lại sẹo. Linh Hồn Cô Đơn vang mọi lời xúc phạm. Nói cẩn trọng và làm im linh hồn.', lesson: 'Lời nói có sức chữa lành hoặc gây hại.' },
    { title: 'Thôn Quà Nhỏ', area: 'Thôn Quà Nhỏ', description: 'Thôn tin chỉ hành động lớn mới đáng. Gương Bản Thể cho thấy sự bỏ bê. Chứng minh bước nhỏ cũng đáng và đối mặt gương.', lesson: 'Hành động tử tế nhỏ bé thay đổi thế giới.' },
    { title: 'Đầm Lầy Vội Vã', area: 'Đầm Lầy Vội Vã', description: 'Đầm lầy nơi mọi người vội và vấp. Bãi Lầy Hối Tiếc sống nhờ sự vội. Chậm lại, giúp người khác chậm lại và làm dịu bãi lầy.', lesson: 'Nhẫn nại là đức tính lớn nhất.' },
    { title: 'Hang Phán Xét', area: 'Hang Phán Xét', description: 'Hang nơi người ta chỉ thấy lỗi. Trái Tim Băng Giá đóng băng mọi ánh nhìn. Học thấy điều tốt và làm tan trái tim.', lesson: 'Hãy thấy ánh sáng nơi người khác.' },
    { title: 'Sa Mạc Ảo Ảnh', area: 'Sa Mạc Ảo Ảnh', description: 'Sa mạc ảo ảnh và hy vọng giả. Chúa Ảo Ảnh cai trị cồn cát. Nhìn xuyên dối trá và đánh bại chúa tể.', lesson: 'Ảo ảnh tan khi bạn nhìn bằng đôi mắt trong.' },
    { title: 'Dốc Vội Vã', area: 'Dốc Vội Vã', description: 'Dốc nơi người chạy ngã vì vội. Kẻ Canh Giữ Xung Đột thưởng tốc độ hơn cẩn trọng. Chứng tỏ bước đều lên đỉnh và đối mặt kẻ canh giữ.', lesson: 'Nỗ lực đều đặn thắng cuộc đua.' },
    { title: 'Tàn Tích Tháp Đồng Hồ', area: 'Tàn Tích Tháp Đồng Hồ', description: 'Tàn tích nơi mọi người sống trong quá khứ hay tương lai. Bóng Nghi Ngờ sống trong đồng hồ. Đưa họ về hiện tại và làm im bóng.', lesson: 'Khoảnh khắc hiện tại là khoảnh khắc duy nhất.' },
    { title: 'Vựa Lúa Kẻ Hà Tiện', area: 'Vựa Lúa Kẻ Hà Tiện', description: 'Vựa đầy lúa không ai chia. Hình Tượng Tham Lam canh cửa. Mở vựa bằng hào phóng và đánh bại hình tượng.', lesson: 'Cho đi nhân lên những gì bạn có.' },
    { title: 'Hải Đăng Cô Độc', area: 'Hải Đăng Cô Độc', description: 'Hải đăng nơi người canh quên thế giới. Linh Hồn Cô Đơn làm mờ ánh sáng. Kết nối lại người canh với đời và đối mặt linh hồn.', lesson: 'Kết nối chữa lành tâm hồn.' },
    // Ch 26–35
    { title: 'Ngã Ba Số Phận', area: 'Ngã Ba Số Phận', description: 'Ngã ba nơi lựa chọn được làm trong sợ. Gương Bản Thể cho thấy cái giá. Chọn với trí tuệ và đối mặt gương.', lesson: 'Lựa chọn của bạn tạo nên con người bạn.' },
    { title: 'Ao Không Yên', area: 'Ao Không Yên', description: 'Ao không bao giờ lặng; không ai thấy bóng mình. Bãi Lầy Hối Tiếc khuấy nước. Mang tĩnh lặng và làm dịu bãi lầy.', lesson: 'Nước lặng phản chiếu trời.' },
    { title: 'Đền Băng', area: 'Đền Băng', description: 'Đền đóng băng vì thờ ơ. Trái Tim Băng Giá ngồi trên bàn thờ. Mang hơi ấm và từ bi để làm tan trái tim.', lesson: 'Hơi ấm làm tan trái tim lạnh nhất.' },
    { title: 'Sảnh Gương', area: 'Sảnh Gương', description: 'Sảnh nơi ảo ảnh nịnh nọt và lừa dối. Chúa Ảo Ảnh cai trị. Thấy sự thật và đánh bại chúa tể.', lesson: 'Hiện thực tử tế hơn ảo ảnh.' },
    { title: 'Đỉnh Vội Vã', area: 'Đỉnh Vội Vã', description: 'Núi nơi người leo bỏ cuộc quá sớm. Kẻ Canh Giữ Xung Đột chế nhạo nỗ lực. Kiên trì từng bước và đối mặt kẻ canh giữ.', lesson: 'Từng bước một lên tới núi.' },
    { title: 'Vườn Ngày Hôm Qua', area: 'Vườn Ngày Hôm Qua', description: 'Vườn mắc kẹt trong ký ức. Bóng Nghi Ngờ sống trong quá khứ. Gieo hạt cho hôm nay và làm im bóng.', lesson: 'Hôm nay là ngày đáng kể.' },
    { title: 'Chợ Nắm Đấm Đóng', area: 'Chợ Nắm Đấm Đóng', description: 'Chợ nơi không ai giao dịch. Hình Tượng Tham Lam khóa sạp. Mở tay mở lòng; đánh bại hình tượng.', lesson: 'Chia sẻ làm đầy cả hai tay.' },
    { title: 'Thung Lũng Chia Rẽ', area: 'Thung Lũng Chia Rẽ', description: 'Thung lũng bị tranh chấp cũ chia đôi. Linh Hồn Cô Đơn giữ hai bên xa. Bắc cầu và đối mặt linh hồn.', lesson: 'Cùng nhau chúng ta mạnh hơn.' },
    { title: 'Võ Đường Bản Ngã', area: 'Võ Đường Bản Ngã', description: 'Võ đường nơi môn sinh đánh vì vinh quang. Gương Bản Thể cho thấy kiêu ngạo. Hạ bản ngã và đối mặt gương.', lesson: 'Làm chủ mình trước khi làm chủ người.' },
    { title: 'Dòng Thác Giận Dữ', area: 'Dòng Thác Giận Dữ', description: 'Thác nơi cơn giận khuấy nước. Bãi Lầy Hối Tiếc ăn cơn thịnh nộ. Mang sự lặng và làm dịu bãi lầy.', lesson: 'Nước lặng chảy sâu.' },
    // Ch 36–45
    { title: 'Hoang Mạc Chế Nhạo', area: 'Hoang Mạc Chế Nhạo', description: 'Hoang mạc nơi lòng tốt bị chế nhạo. Trái Tim Băng Giá cai trị. Gieo lòng tốt và làm tan trái tim.', lesson: 'Lòng tốt không bao giờ uổng.' },
    { title: 'Mê Cung Dối Trá', area: 'Mê Cung Dối Trá', description: 'Mê cung xây trên dối trá. Chúa Ảo Ảnh canh trung tâm. Nói sự thật và đánh bại chúa tể.', lesson: 'Sự thật là bước đầu tới tự do.' },
    { title: 'Bãi Biển Vội Vã', area: 'Bãi Biển Vội Vã', description: 'Bãi biển nơi không ai đợi thủy triều. Kẻ Canh Giữ Xung Đột thúc mọi người. Dạy nhẫn nại và đối mặt kẻ canh giữ.', lesson: 'Nhẫn nại biến cát thành ngọc.' },
    { title: 'Quán Trọ Ngày Mai', area: 'Quán Trọ Ngày Mai', description: 'Quán trọ nơi khách chỉ lên kế hoạch cho ngày mai. Bóng Nghi Ngờ sống trong kế hoạch. Sống trong hiện tại và làm im bóng.', lesson: 'Hiện tại là nhà duy nhất của bạn.' },
    { title: 'Đền Thập Phân', area: 'Đền Thập Phân', description: 'Đền đòi trả giá cho mọi phước lành. Hình Tượng Tham Lam đếm từng đồng. Cho đi không mong đáp và đánh bại hình tượng.', lesson: 'Cho mà không mong nhận lại.' },
    { title: 'Đảo Thờ ơ', area: 'Đảo Thờ ơ', description: 'Đảo nơi không ai giúp ai. Linh Hồn Cô Đơn phát triển. Đưa tay và đối mặt linh hồn.', lesson: 'Bạn trong lúc hoạn nạn mới là bạn thật.' },
    { title: 'Đền Ngủ Say', area: 'Đền Ngủ Say', description: 'Đền nơi không ai nhìn vào trong. Gương Bản Thể chờ. Xét mình và đối mặt gương.', lesson: 'Cuộc đời không xét lại không đáng sống.' },
    { title: 'Chợ Ồn Ào', area: 'Chợ Ồn Ào', description: 'Chợ ồn đến mức không ai nghe được mình. Bãi Lầy Hối Tiếc thêm vào ồn. Tìm tĩnh lặng và làm dịu bãi lầy.', lesson: 'Tĩnh lặng hé lộ điều ồn ào che.' },
    { title: 'Cánh Đồng Tuyết Cô Độc', area: 'Cánh Đồng Tuyết Cô Độc', description: 'Cánh đồng tuyết nơi mọi người cô đơn. Trái Tim Băng Giá giữ lạnh. Mang tình thương và làm tan trái tim.', lesson: 'Tình thương làm tan mùa đông lạnh nhất.' },
    { title: 'Sương Kinh Sợ', area: 'Sương Kinh Sợ', description: 'Sương mà sợ làm dày. Chúa Ảo Ảnh ăn nỗi kinh sợ. Bước với dũng khí và làm tan chúa tể.', lesson: 'Nhìn xuyên màn sợ hãi.' },
    // Ch 46–55
    { title: 'Cuộc Chạy Vội', area: 'Cuộc Chạy Vội', description: 'Cuộc chạy nơi mọi người vấp vì tốc độ. Kẻ Canh Giữ Xung Đột cổ vũ kẻ liều. Chạy cẩn trọng và đối mặt kẻ canh giữ.', lesson: 'Chậm mà chắc thắng.' },
    { title: 'Nghĩa Địa Thù Hận', area: 'Nghĩa Địa Thù Hận', description: 'Nghĩa địa nơi thù hận vẫn được chăm. Bóng Nghi Ngờ chăm các mộ. Để người đã khuất yên nghỉ và làm im bóng.', lesson: 'Để quá khứ yên nghỉ.' },
    { title: 'Hầm Kẻ Tích Trữ', area: 'Hầm Kẻ Tích Trữ', description: 'Hầm đầy vàng không ai dùng. Hình Tượng Tham Lam ngủ trên đống. Chia của và đánh bại hình tượng.', lesson: 'Của cải chia sẻ là của cải nhân đôi.' },
    { title: 'Quần Đảo Kiêu Ngạo', area: 'Quần Đảo Kiêu Ngạo', description: 'Các đảo từ chối bắc cầu. Linh Hồn Cô Đơn cai trị eo biển. Kết nối các đảo và đối mặt linh hồn.', lesson: 'Không ai là một hòn đảo.' },
    { title: 'Đấu Trường Thịnh Nộ', area: 'Đấu Trường Thịnh Nộ', description: 'Đấu trường nơi võ sĩ đánh mất mình vì giận. Gương Bản Thể phản chiếu cơn thịnh nộ. Tìm sự làm chủ và đối mặt gương.', lesson: 'Sức mạnh thật là làm chủ bản thân.' },
    { title: 'Hẻm Núi Ồn Ào', area: 'Hẻm Núi Ồn Ào', description: 'Hẻm núi ồn vô tận. Bãi Lầy Hối Tiếc khuếch đại âm thanh. Tìm im lặng và làm dịu bãi lầy.', lesson: 'Tĩnh tâm để nghe tim.' },
    { title: 'Pháo Đài Sợ Hãi', area: 'Pháo Đài Sợ Hãi', description: 'Pháo đài xây bởi sợ. Trái Tim Băng Giá canh cổng. Tiếp cận bằng từ bi và làm tan trái tim.', lesson: 'Từ bi là dũng khí.' },
    { title: 'Sảnh Hóa Trang', area: 'Sảnh Hóa Trang', description: 'Sảnh nơi mọi người đeo mặt nạ. Chúa Ảo Ảnh yêu sự ngụy trang. Bỏ mặt nạ và đánh bại chúa tể.', lesson: 'Hiện thực không cần ngụy trang.' },
    { title: 'Ngưỡng Nghi Ngờ', area: 'Ngưỡng Nghi Ngờ', description: 'Ngưỡng không ai dám bước qua. Kẻ Canh Giữ Xung Đột chặn lối. Bước bước đầu và đối mặt kẻ canh giữ.', lesson: 'Mọi hành trình bắt đầu bằng một bước.' },
    { title: 'Cơn Hen Lo Âu', area: 'Cơn Hen Lo Âu', description: 'Nơi nỗi lo cướp từng hơi thở. Bóng Nghi Ngờ thì thầm "nếu như". Thở trong hiện tại và làm im bóng.', lesson: 'Hơi thở hôm nay là món quà hôm nay.' },
    // Ch 56–65
    { title: 'Giếng Tham Lam', area: 'Giếng Tham Lam', description: 'Giếng cạn vì tích trữ. Hình Tượng Tham Lam canh gàu. Cho trước và đánh bại hình tượng.', lesson: 'Càng cho càng có.' },
    { title: 'Bóng Tối Chia Rẽ', area: 'Bóng Tối Chia Rẽ', description: 'Nơi nghi ngờ chia rẽ. Linh Hồn Cô Đơn làm tối mọi góc. Đoàn kết và thắp sáng; đối mặt linh hồn.', lesson: 'Đoàn kết tạo ra ánh sáng.' },
    { title: 'Mê Cung Gương', area: 'Mê Cung Gương', description: 'Mê cung phản chiếu. Gương Bản Thể giấu lối ra. Biết mình là ai và đối mặt gương.', lesson: 'Hãy biết chính mình.' },
    { title: 'Doanh Trại Chiến Tranh', area: 'Doanh Trại Chiến Tranh', description: 'Doanh trại nơi chiến tranh không bao giờ dứt. Bãi Lầy Hối Tiếc tiếp thêm cho trận. Luyện bình yên và làm dịu bãi lầy.', lesson: 'Bình yên là sự luyện tập.' },
    { title: 'Cầu Thu Phí', area: 'Cầu Thu Phí', description: 'Cầu nơi mỗi lần qua đều có giá. Trái Tim Băng Giá thu phí. Dâng lòng tốt thay vì tiền và làm tan trái tim.', lesson: 'Lòng tốt không tốn gì.' },
    { title: 'Nhà Tù Giả Vờ', area: 'Nhà Tù Giả Vờ', description: 'Nhà tù xây trên giả vờ. Chúa Ảo Ảnh là cai ngục. Nói sự thật và thoát; đánh bại chúa tể.', lesson: 'Sự thật giải phóng bạn.' },
    { title: 'Vụ Hái Vội', area: 'Vụ Hái Vội', description: 'Vụ mùa hỏng vì hái quá sớm. Kẻ Canh Giữ Xung Đột thúc tốc độ. Đợi chín và đối mặt kẻ canh giữ.', lesson: 'Hãy đợi đúng thời điểm.' },
    { title: 'Ngục Ký ức', area: 'Ngục Ký ức', description: 'Ngục nơi quá khứ xiềng hiện tại. Bóng Nghi Ngờ giữ chìa khóa. Học và buông; làm im bóng.', lesson: 'Quá khứ là thầy, không phải nhà tù.' },
    { title: 'Nhà Đếm', area: 'Nhà Đếm', description: 'Nhà nơi mọi món quà bị cân đo. Hình Tượng Tham Lam giữ sổ. Cho không đếm và đánh bại hình tượng.', lesson: 'Hãy cho từ trái tim.' },
    { title: 'Đỉnh Ẩn Sĩ', area: 'Đỉnh Ẩn Sĩ', description: 'Đỉnh nơi ẩn sĩ quên người khác. Linh Hồn Cô Đơn sống trong hang. Nhắc ẩn sĩ về kết nối và đối mặt linh hồn.', lesson: 'Chúng ta cần nhau.' },
    // Ch 66–75
    { title: 'Cổng Kiêu Ngạo', area: 'Cổng Kiêu Ngạo', description: 'Cổng mà kiêu hãnh khóa. Gương Bản Thể canh. Tiếp cận với khiêm nhường và đối mặt gương.', lesson: 'Khiêm nhường mở cửa.' },
    { title: 'Tháp Lưỡi', area: 'Tháp Lưỡi', description: 'Tháp nơi không ai ngừng nói. Bãi Lầy Hối Tiếc thêm vào ồn. Ôm im lặng và làm dịu bãi lầy.', lesson: 'Im lặng lên tiếng.' },
    { title: 'Bức Tường Người Lạ', area: 'Bức Tường Người Lạ', description: 'Tường ngăn hàng xóm. Trái Tim Băng Giá xây nó. Phá bằng tình thương và làm tan trái tim.', lesson: 'Hãy yêu người lân cận như chính mình.' },
    { title: 'Bữa Tiệc Bóng Ma', area: 'Bữa Tiệc Bóng Ma', description: 'Bữa tiệc trông thật nhưng khiến mọi người đói. Chúa Ảo Ảnh dọn đĩa. Tìm dưỡng chất thật và đánh bại chúa tể.', lesson: 'Ảo ảnh không thể nuôi kẻ đói.' },
    { title: 'Mỏ Đá Kẻ Bỏ Cuộc', area: 'Mỏ Đá Kẻ Bỏ Cuộc', description: 'Mỏ đá bị bỏ quá sớm. Kẻ Canh Giữ Xung Đột chế nhạo thợ. Trở lại và kiên trì; đối mặt kẻ canh giữ.', lesson: 'Kiên trì dời non.' },
    { title: 'Phòng Chờ', area: 'Phòng Chờ', description: 'Phòng nơi mọi người chờ "một ngày nào đó." Bóng Nghi Ngờ nói "chưa phải." Hành động ngay và làm im bóng.', lesson: 'Bây giờ là lúc.' },
    { title: 'Đập Tham Lam', area: 'Đập Tham Lam', description: 'Đập chặn dòng dồi dào. Hình Tượng Tham Lam điều khiển cổng. Mở cổng và đánh bại hình tượng.', lesson: 'Dồi dào chảy khi chia sẻ.' },
    { title: 'Hố Chia Rẽ', area: 'Hố Chia Rẽ', description: 'Hố nơi người chia rẽ rơi. Linh Hồn Cô Đơn đào hố sâu. Đoàn kết và leo; đối mặt linh hồn.', lesson: 'Cùng nhau chúng ta vươn lên.' },
    { title: 'Ngai Bốc Đồng', area: 'Ngai Bốc Đồng', description: 'Ngai nơi bốc đồng ngự trị. Gương Bản Thể ngồi đó. Làm chủ mình và đối mặt gương.', lesson: 'Kẻ trí làm chủ mình.' },
    { title: 'Chiến Trường Thần Kinh', area: 'Chiến Trường Thần Kinh', description: 'Chiến trường suy nghĩ lo âu. Bãi Lầy Hối Tiếc tiếp thêm chiến tranh. Tìm bình an nội tâm và làm dịu bãi lầy.', lesson: 'Bình an nội tâm, bình an bên ngoài.' },
    // Ch 76–85
    { title: 'Cánh Đồng Tê Cóng', area: 'Cánh Đồng Tê Cóng', description: 'Cánh đồng lạnh lan từ trái tim lạnh. Trái Tim Băng Giá cai trị. Mang hơi ấm và làm tan trái tim.', lesson: 'Hơi ấm sinh hơi ấm.' },
    { title: 'Cung Điện Mộng', area: 'Cung Điện Mộng', description: 'Cung điện xây trên mộng bỏ qua hiện thực. Chúa Ảo Ảnh trang trí sảnh. Tỉnh dậy và đánh bại chúa tể.', lesson: 'Hãy đối mặt điều thật.' },
    { title: 'Đỉnh Thở Dốc', area: 'Đỉnh Thở Dốc', description: 'Đỉnh nơi người leo thở hổn hển rồi bỏ. Kẻ Canh Giữ Xung Đột đẩy quá mạnh. Thở, bước và đối mặt kẻ canh giữ.', lesson: 'Một hơi, một bước.' },
    { title: 'Dòng Sông Hối Tiếc', area: 'Dòng Sông Hối Tiếc', description: 'Dòng sông chảy ngược về quá khứ. Bóng Nghi Ngờ bơi trong đó. Để sông chảy tới và làm im bóng.', lesson: 'Buông điều không thể thay đổi.' },
    { title: 'Xích Sở Hữu', area: 'Xích Sở Hữu', description: 'Xích chấp trước. Hình Tượng Tham Lam rèn mắt xích. Buông và cho; đánh bại hình tượng.', lesson: 'Hào phóng là tự do.' },
    { title: 'Mạng Người Lạ', area: 'Mạng Người Lạ', description: 'Mạng nơi mỗi sợi đơn lẻ. Linh Hồn Cô Đơn dệt. Kết nối các sợi và đối mặt linh hồn.', lesson: 'Chúng ta đều kết nối.' },
    { title: 'Tu Viện Hỗn Loạn', area: 'Tu Viện Hỗn Loạn', description: 'Tu viện nơi tâm trí chạy rong. Gương Bản Thể nhân hỗn loạn. Làm chủ tâm và đối mặt gương.', lesson: 'Làm chủ tâm trí.' },
    { title: 'Quảng Trường Lốc Xoáy', area: 'Quảng Trường Lốc Xoáy', description: 'Quảng trường chuyển động không ngừng. Bãi Lầy Hối Tiếc xoay ở trung tâm. Tìm tĩnh lặng trong và làm dịu bãi lầy.', lesson: 'Tĩnh lặng trong chuyển động.' },
    { title: 'Hang Kinh Sợ', area: 'Hang Kinh Sợ', description: 'Hang nơi sợ làm nhà. Trái Tim Băng Giá nuôi nỗi kinh sợ. Bước vào với từ bi và làm tan trái tim.', lesson: 'Từ bi chinh phục sợ hãi.' },
    { title: 'Hang Mạ Vàng', area: 'Hang Mạ Vàng', description: 'Hang phủ vàng giả. Chúa Ảo Ảnh sơn tường. Thấy điều thật và đánh bại chúa tể.', lesson: 'Bóc đi điều giả.' },
    // Ch 86–95
    { title: 'Cuộc Chạy Tuyệt Vọng', area: 'Cuộc Chạy Tuyệt Vọng', description: 'Cuộc chạy làm gục tinh thần. Kẻ Canh Giữ Xung Đột chạy bên bạn. Chịu đựng và về đích; đối mặt kẻ canh giữ.', lesson: 'Chịu đựng thắng.' },
    { title: 'Cung Điện Thêm Nữa', area: 'Cung Điện Thêm Nữa', description: 'Cung điện nơi thêm không bao giờ đủ. Bóng Nghi Ngờ sống trong hầm. Thấy đủ trong hiện tại và làm im bóng.', lesson: 'Khoảnh khắc này là đủ.' },
    { title: 'Đường Đơn Độc', area: 'Đường Đơn Độc', description: 'Con đường dành cho nhiều người nhưng chỉ một đi. Hình Tượng Tham Lam cướp phần còn lại. Chia sẻ đường và đánh bại hình tượng.', lesson: 'Hãy chia sẻ hành trình.' },
    { title: 'Đảo Giường Bệnh', area: 'Đảo Giường Bệnh', description: 'Đảo người bệnh từ chối giúp đỡ. Linh Hồn Cô Đơn chăm họ. Dâng sự chữa lành và đối mặt linh hồn.', lesson: 'Không ai lành bệnh một mình.' },
    { title: 'Cổng Vòm Chiến Thắng', area: 'Cổng Vòm Chiến Thắng', description: 'Cổng vòm tôn vinh bản thân. Gương Bản Thể đứng dưới. Đặt vương miện xuống và đối mặt gương.', lesson: 'Bản ngã là kẻ thù duy nhất.' },
    { title: 'Tháp Ồn Ào', area: 'Tháp Ồn Ào', description: 'Tháp nơi suy nghĩ không ngừng. Bãi Lầy Hối Tiếc thêm vào ồn. Tĩnh tâm và làm dịu bãi lầy.', lesson: 'Tâm lặng, đường rõ.' },
    { title: 'Pháo Đài Biên Giới', area: 'Pháo Đài Biên Giới', description: 'Pháo đài đẩy người ra. Trái Tim Băng Giá giữ chìa khóa. Mở cổng bằng tình thương và làm tan trái tim.', lesson: 'Tình thương vượt mọi biên giới.' },
    { title: 'Kho Vũ Khí Dối Trá', area: 'Kho Vũ Khí Dối Trá', description: 'Kho trang bị bằng dối trá. Chúa Ảo Ảnh đánh bóng vũ khí. Giải giáp bằng sự thật và đánh bại chúa tể.', lesson: 'Sự thật không cần áo giáp.' },
    { title: 'Thung Lũng Chạy Nước Rút', area: 'Thung Lũng Chạy Nước Rút', description: 'Thung lũng nơi mọi người chạy và ngã. Kẻ Canh Giữ Xung Đột thưởng kẻ nhanh nhất. Bước với nhẫn nại và đối mặt kẻ canh giữ.', lesson: 'Nhẫn nại là sức mạnh.' },
    { title: 'Thư Phòng Số Phận', area: 'Thư Phòng Số Phận', description: 'Thư phòng nơi số phận viết bằng đá. Bóng Nghi Ngờ cầm bút. Viết lại bằng hy vọng và làm im bóng.', lesson: 'Tương lai chưa được viết.' },
    // Ch 96–100
    { title: 'Kho Báu Nắm Đấm', area: 'Kho Báu Nắm Đấm', description: 'Kho báu nắm trong tay đóng. Hình Tượng Tham Lam bẩy mở. Mở tay và đánh bại hình tượng.', lesson: 'Tay mở nhận thêm.' },
    { title: 'Cơn Bão Cô Độc', area: 'Cơn Bão Cô Độc', description: 'Cơn bão cô lập mọi người. Linh Hồn Cô Đơn cưỡi gió. Xây nơi trú cùng nhau và đối mặt linh hồn.', lesson: 'Cộng đồng là nơi trú ẩn.' },
    { title: 'Đấu Trường Chinh Phục', area: 'Đấu Trường Chinh Phục', description: 'Đấu trường tôn vinh chinh phục. Gương Bản Thể trao vương miện. Chiến thắng chính mình và đối mặt gương.', lesson: 'Chiến thắng lớn nhất là chiến thắng chính mình.' },
    { title: 'Tro Bại Trận', area: 'Tro Bại Trận', description: 'Tro thất bại trước. Bãi Lầy Hối Tiếc khuấy tro. Thở và bắt đầu lại; làm dịu bãi lầy.', lesson: 'Thở và bắt đầu lại.' },
    { title: 'Cầu Thang Chế Nhạo', area: 'Cầu Thang Chế Nhạo', description: 'Cầu thang mỗi bậc là khinh miệt. Trái Tim Băng Giá xây. Leo với lòng tốt và làm tan trái tim.', lesson: 'Lòng tốt là bước đầu.' },
];
