/**
 * Registry mapping skill names and variants to their effect module paths.
 * Used for lazy-loading effects via dynamic import() - avoids loading all ~67
 * effect classes at startup for significant performance improvement.
 */

/** Base skill name -> { modulePath, exportName } */
export const BASE_EFFECT_REGISTRY = {
    'Wave Strike': { path: 'WaveStrikeEffect.js', exportName: 'WaveStrikeEffect' },
    'Cyclone Strike': { path: 'CycloneStrikeEffect.js', exportName: 'CycloneStrikeEffect' },
    'Seven-Sided Strike': { path: 'SevenSidedStrikeEffect.js', exportName: 'SevenSidedStrikeEffect' },
    'Fist of Thunder': { path: 'FistOfThunderEffect.js', exportName: 'FistOfThunderEffect' },
    'Inner Sanctuary': { path: 'InnerSanctuaryEffect.js', exportName: 'InnerSanctuaryEffect' },
    'Wave of Light': { path: 'WaveOfLightEffect.js', exportName: 'WaveOfLightEffect' },
    'Mystic Allies': { path: 'MysticAllyEffect.js', exportName: 'MysticAllyEffect' },
    'Exploding Palm': { path: 'ExplodingPalmEffect.js', exportName: 'ExplodingPalmEffect' },
    'Breath of Heaven': { path: 'BreathOfHeavenEffect.js', exportName: 'BreathOfHeavenEffect' },
    'Shield of Zen': { path: 'ShieldOfZenEffect.js', exportName: 'ShieldOfZenEffect' },
    'Flying Dragon': { path: 'FlyingDragonEffect.js', exportName: 'FlyingDragonEffect' },
    'Flying Kick': { path: 'FlyingKickEffect.js', exportName: 'FlyingKickEffect' },
    'Deadly Reach': { path: 'DeadlyReachEffect.js', exportName: 'DeadlyReachEffect' },
    'Imprisoned Fists': { path: 'ImprisonedFistsEffect.js', exportName: 'ImprisonedFistsEffect' },
    'Bul Palm': { path: 'BulPalmEffect.js', exportName: 'BulPalmEffect' },
    'Bul Breath Of Heaven': { path: 'BulBreathOfHeavenEffect.js', exportName: 'BulBreathOfHeavenEffect' },
    'Bul Shadow Clone': { path: 'BulShadowCloneEffect.js', exportName: 'BulShadowCloneEffect' }
};

/** (skillName, variantName) -> { modulePath, exportName } - variant effects */
export const VARIANT_EFFECT_REGISTRY = {
    'Breath of Heaven|Circle of Life': { path: 'variants/BreathOfHeaven/CircleOfLifeEffect.js', exportName: 'CircleOfLifeEffect' },
    'Breath of Heaven|Infused with Light': { path: 'variants/BreathOfHeaven/InfusedWithLightEffect.js', exportName: 'InfusedWithLightEffect' },
    'Breath of Heaven|Radiant Breath': { path: 'variants/BreathOfHeaven/RadiantBreathEffect.js', exportName: 'RadiantBreathEffect' },
    'Breath of Heaven|Soothing Mist': { path: 'variants/BreathOfHeaven/SoothingMistEffect.js', exportName: 'SoothingMistEffect' },
    "Breath of Heaven|Zephyr's Grace": { path: 'variants/BreathOfHeaven/ZephyrsGraceEffect.js', exportName: 'ZephyrsGraceEffect' },
    'Cyclone Strike|Eye of the Storm': { path: 'variants/CycloneStrike/EyeOfTheStormEffect.js', exportName: 'EyeOfTheStormEffect' },
    'Cyclone Strike|Path of the Storm': { path: 'variants/CycloneStrike/PathOfTheStormEffect.js', exportName: 'PathOfTheStormEffect' },
    'Cyclone Strike|Storm Spirit': { path: 'variants/CycloneStrike/StormSpiritEffect.js', exportName: 'StormSpiritEffect' },
    "Cyclone Strike|Tempest's Heart": { path: 'variants/CycloneStrike/TempestsHeartEffect.js', exportName: 'TempestsHeartEffect' },
    'Exploding Palm|Crippling Insight': { path: 'variants/ExplodingPalm/CripplingInsightEffect.js', exportName: 'CripplingInsightEffect' },
    'Exploding Palm|Reaching Rebuke': { path: 'variants/ExplodingPalm/ReachingRebukeEffect.js', exportName: 'ReachingRebukeEffect' },
    'Exploding Palm|Scolding Storm': { path: 'variants/ExplodingPalm/ScoldingStormEffect.js', exportName: 'ScoldingStormEffect' },
    'Exploding Palm|Breath of Incense': { path: 'variants/ExplodingPalm/BreathOfIncenseEffect.js', exportName: 'BreathOfIncenseEffect' },
    'Exploding Palm|Path of the Present': { path: 'variants/ExplodingPalm/PathOfThePresentEffect.js', exportName: 'PathOfThePresentEffect' },
    "Flying Dragon|Dragon's Flight": { path: 'variants/FlyingDragon/DragonFlightEffect.js', exportName: 'DragonFlightEffect' },
    'Flying Dragon|Inferno Dragon': { path: 'variants/FlyingDragon/InfernoDragonEffect.js', exportName: 'InfernoDragonEffect' },
    'Flying Dragon|Thunder Dragon': { path: 'variants/FlyingDragon/ThunderDragonEffect.js', exportName: 'ThunderDragonEffect' },
    'Flying Dragon|Gale Dragon': { path: 'variants/FlyingDragon/GaleDragonEffect.js', exportName: 'GaleDragonEffect' },
    'Flying Dragon|Shadow Dragon': { path: 'variants/FlyingDragon/ShadowDragonEffect.js', exportName: 'ShadowDragonEffect' },
    'Flying Kick|Mantle of the Crane': { path: 'variants/FlyingKick/MantleOfTheCraneEffect.js', exportName: 'MantleOfTheCraneEffect' },
    "Flying Kick|Tiger's Flight": { path: 'variants/FlyingKick/TigersFlightEffect.js', exportName: 'TigersFlightEffect' },
    "Flying Kick|Grace's Bounty": { path: 'variants/FlyingKick/GracesBountyEffect.js', exportName: 'GracesBountyEffect' },
    "Flying Kick|Momentum's Flow": { path: 'variants/FlyingKick/MomentumFlowEffect.js', exportName: 'MomentumFlowEffect' },
    'Flying Kick|Spokes of the Wheel': { path: 'variants/FlyingKick/SpokesOfTheWheelEffect.js', exportName: 'SpokesOfTheWheelEffect' },
    'Inner Sanctuary|Circle of Wrath': { path: 'variants/InnerSanctuary/CircleOfWrathEffect.js', exportName: 'CircleOfWrathEffect' },
    'Inner Sanctuary|Sanctified Ground': { path: 'variants/InnerSanctuary/SanctifiedGroundEffect.js', exportName: 'SanctifiedGroundEffect' },
    'Inner Sanctuary|Safe Haven': { path: 'variants/InnerSanctuary/SafeHavenEffect.js', exportName: 'SafeHavenEffect' },
    'Inner Sanctuary|Temple of Protection': { path: 'variants/InnerSanctuary/TempleOfProtectionEffect.js', exportName: 'TempleOfProtectionEffect' },
    'Inner Sanctuary|Forbidden Palace': { path: 'variants/InnerSanctuary/ForbiddenPalaceEffect.js', exportName: 'ForbiddenPalaceEffect' },
    'Mystic Allies|Fire Allies': { path: 'variants/MysticAllies/FireAlliesEffect.js', exportName: 'FireAlliesEffect' },
    'Mystic Allies|Water Allies': { path: 'variants/MysticAllies/WaterAlliesEffect.js', exportName: 'WaterAlliesEffect' },
    'Imprisoned Fists|Thunderous Grip': { path: 'variants/ImprisonedFists/ThunderousGripEffect.js', exportName: 'ThunderousGripEffect' },
    'Imprisoned Fists|Frozen Shackles': { path: 'variants/ImprisonedFists/FrozenShacklesEffect.js', exportName: 'FrozenShacklesEffect' },
    'Imprisoned Fists|Shadow Bind': { path: 'variants/ImprisonedFists/ShadowBindEffect.js', exportName: 'ShadowBindEffect' },
    'Imprisoned Fists|Gale Chains': { path: 'variants/ImprisonedFists/GaleChainsEffect.js', exportName: 'GaleChainsEffect' },
    'Imprisoned Fists|Fiery Chains': { path: 'variants/ImprisonedFists/FieryChainsEffect.js', exportName: 'FieryChainsEffect' },
    'Wave Strike|Tidal Force': { path: 'variants/WaveStrike/TidalWaveEffect.js', exportName: 'TidalWaveEffect' },
    'Wave Strike|Shocking Wave': { path: 'variants/WaveStrike/ThunderWaveEffect.js', exportName: 'ThunderWaveEffect' },
    'Wave Strike|Freezing Wave': { path: 'variants/WaveStrike/FrozenWaveEffect.js', exportName: 'FrozenWaveEffect' },
    'Seven-Sided Strike|Blazing Fists': { path: 'variants/SevenSidedStrike/ShadowAssaultEffect.js', exportName: 'ShadowAssaultEffect' },
    'Seven-Sided Strike|Frozen Assault': { path: 'variants/SevenSidedStrike/SustainedAssaultEffect.js', exportName: 'SustainedAssaultEffect' },
    'Seven-Sided Strike|Thunderclap': { path: 'variants/SevenSidedStrike/FistOfFuryEffect.js', exportName: 'FistOfFuryEffect' },
    'Seven-Sided Strike|Phantom Echo': { path: 'variants/SevenSidedStrike/PandemoniumEffect.js', exportName: 'PandemoniumEffect' },
    'Seven-Sided Strike|Celestial Impact': { path: 'variants/SevenSidedStrike/InnerPeaceEffect.js', exportName: 'InnerPeaceEffect' },
    'Shield of Zen|Transcendence': { path: 'variants/ShieldOfZen/TranscendenceEffect.js', exportName: 'TranscendenceEffect' },
    'Shield of Zen|Retribution Aura': { path: 'variants/ShieldOfZen/RetributionAuraEffect.js', exportName: 'RetributionAuraEffect' },
    'Shield of Zen|Spiritual Protection': { path: 'variants/ShieldOfZen/SpiritualProtectionEffect.js', exportName: 'SpiritualProtectionEffect' },
    'Shield of Zen|Diamond Aura': { path: 'variants/ShieldOfZen/DiamondAuraEffect.js', exportName: 'DiamondAuraEffect' },
    'Wave of Light|Explosive Light': { path: 'variants/WaveOfLight/ExplosiveLightEffect.js', exportName: 'ExplosiveLightEffect' },
    'Wave of Light|Lightning Bell': { path: 'variants/WaveOfLight/LightningBellEffect.js', exportName: 'LightningBellEffect' },
    'Wave of Light|Pillar of the Light': { path: 'variants/WaveOfLight/PillarOfTheLightEffect.js', exportName: 'PillarOfTheLightEffect' },
    'Wave of Light|Wall of Light': { path: 'variants/WaveOfLight/WallOfLightEffect.js', exportName: 'WallOfLightEffect' },
    'Bul Palm|Palm Rain': { path: 'variants/BulPalm/BulPalmRainEffect.js', exportName: 'BulPalmRainEffect' },
    'Bul Palm|Palm Cross': { path: 'variants/BulPalm/BulPalmCrossEffect.js', exportName: 'BulPalmCrossEffect' },
    'Bul Palm|Storm of Palms': { path: 'variants/BulPalm/StormOfPalmsEffect.js', exportName: 'StormOfPalmsEffect' }
};
